/* ══════════════════════════════════════════════════════════════════════
   apa-geo.js — Cabana's location layer.

   Every box on this platform where a human types a place goes through
   this file: the search bar on apartments, the address step of a
   listing, a ride's pick-up, an event venue, a tour's meeting point.
   Before it existed, each of those had invented its own answer — a
   hardcoded list of thirty-six cities here, a Nairobi-only gazetteer
   there, a dead reference to a Google API key nobody ever set. A host
   in Lisbon could not describe where their flat was, and a guest who
   typed "Diani" got nothing because the listing said "Ukunda".

   Now there is one answer, and it covers the planet.

     ApaGeo.search(q, o)          → Promise<Place[]>
     ApaGeo.reverse(lat, lng)     → Promise<Place|null>
     ApaGeo.attach(input, o)      → typeahead on any input
     ApaGeo.autoWire(root)        → attach to every [data-apa-geo]
     ApaGeo.locate()              → the device's own fix, reverse-coded
     ApaGeo.distance(a, b)        → kilometres
     ApaGeo.nearby(items, c, o)   → what is close, and how close
     ApaGeo.match(item, place, o) → does this listing satisfy this search
     ApaGeo.parse(text)           → best guess for a record with no pin

   FOUR THINGS THIS FILE IS BUILT AROUND
   ─────────────────────────────────────

   1. An answer on the first keystroke, always.
      A network geocode takes 200-600ms and sometimes never arrives. So
      every query is answered instantly from a gazetteer compiled from
      Cabana's own place graph — every city, neighbourhood and safari
      region the platform sells — and the network result merges in when
      it lands. The box is never empty and never blocks.

   2. Coordinates, not strings.
      A picked place carries lat/lng from here to the database. Text
      matching is what made "Diani" and "Ukunda" different places and
      "Karen" and "Karen, Nairobi" different searches. Once a search has
      a point, matching is arithmetic: a listing is in range or it is not.

   3. Nothing is ever a dead end.
      No exact match widens the radius rather than showing nothing —
      the way a guest actually thinks, which is "well, what is near
      there?" A provider outage falls back to the next provider, then to
      the gazetteer. A refused location permission falls back to typing.

   4. Coordinates are dropped the moment the text stops describing them.
      A guest picks "Westlands, Nairobi", then edits the box to read
      "Mombasa" and hits search. The single most common bug in every
      location widget ever shipped is sending Westlands' coordinates
      with Mombasa's label. Editing after a pick clears the pin.
══════════════════════════════════════════════════════════════════════ */
(function () {
  'use strict';

  if (window.ApaGeo) return;

  var API        = '/api/geocode';
  var MIN_CHARS  = 2;
  var DEBOUNCE   = 220;
  var RECENT_MAX = 6;
  var RECENT_KEY = 'apa_geo_recent';
  var BIAS_KEY   = 'apa_geo_bias';

  /* Direct-to-provider fallbacks, used only when our own route is
     unreachable — a preview build, a static mirror, an API outage.
     Photon and Nominatim both send CORS headers, so the browser can
     talk to them; it just cannot identify itself the way the server
     does, which is why this is the fallback and not the path. */
  var PHOTON = 'https://photon.komoot.io/api';
  var NOMINATIM = 'https://nominatim.openstreetmap.org/search';

  /* ════════════════════════════════════════════════════════════════
     1 · GAZETTEER

     Compiled from seo/data/places.py and seo/data/africa.py by
     seo/build_gazetteer.py — the same place graph that builds the
     landing pages, so a city that has a page is a city guests can
     search for, permanently and by construction.

     Columns: name, parent, country, iso2, lat, lng, kind
     ════════════════════════════════════════════════════════════════ */

  /* GAZETTEER:BEGIN — generated by seo/build_gazetteer.py, do not hand-edit */
  var SEED = [
    ['Abidjan','','Côte d\'Ivoire','ci',5.3204,-4.0161,'city'],
    ['Abomey','','Benin','bj',7.182,1.9936,'city'],
    ['Abuja','','Nigeria','ng',9.0643,7.4893,'city'],
    ['Abéché','','Chad','td',13.828,20.8284,'city'],
    ['Accra','','Ghana','gh',5.5571,-0.2012,'city'],
    ['Addis Ababa','','Ethiopia','et',9.0,38.75,'city'],
    ['Agadez','','Niger','ne',16.9726,7.9907,'city'],
    ['Agadir','','Morocco','ma',30.4205,-9.5839,'city'],
    ['Alexandria','','Egypt','eg',31.1992,29.8952,'city'],
    ['Algiers','','Algeria','dz',36.7729,3.0588,'city'],
    ['Amsterdam','Amsterdam','Netherlands','nl',52.3676,4.9041,'city'],
    ['Antananarivo','','Madagascar','mg',-18.91,47.5256,'city'],
    ['Arusha','','Tanzania','tz',-3.3697,36.6881,'city'],
    ['Asmara','','Eritrea','er',15.339,38.9327,'city'],
    ['Aswan','','Egypt','eg',24.0911,32.8973,'city'],
    ['Atar','','Mauritania','mr',20.5182,-13.0544,'city'],
    ['Athens','Athens','Greece','gr',37.9838,23.7275,'city'],
    ['Bahir Dar','','Ethiopia','et',11.595,37.3882,'city'],
    ['Bali','Denpasar','Indonesia','id',-8.4095,115.1889,'city'],
    ['Bamako','','Mali','ml',12.6493,-8.0003,'city'],
    ['Bamenda','','Cameroon','cm',5.9614,10.1517,'city'],
    ['Bangkok','Bangkok','Thailand','th',13.7563,100.5018,'city'],
    ['Bangui','','Central African Republic','cf',4.3635,18.5836,'city'],
    ['Banjul','','Gambia','gm',13.441,-16.5628,'city'],
    ['Barcelona','Barcelona','Spain','es',41.3851,2.1734,'city'],
    ['Bata','','Equatorial Guinea','gq',2.0064,9.9088,'city'],
    ['Beau Vallon','','Seychelles','sc',-4.6096,55.4381,'city'],
    ['Beira','','Mozambique','mz',-19.8341,34.8358,'city'],
    ['Belle Mare','','Mauritius','mu',-20.1983,57.7747,'city'],
    ['Benghazi','','Libya','ly',32.12,20.0812,'city'],
    ['Benguela','','Angola','ao',-12.579,13.4037,'city'],
    ['Benin City','','Nigeria','ng',6.3331,5.6221,'city'],
    ['Berbera','','Somalia','so',10.4386,45.0134,'city'],
    ['Berlin','Berlin','Germany','de',52.52,13.405,'city'],
    ['Bissau','','Guinea-Bissau','gw',11.8613,-15.5831,'city'],
    ['Blantyre','','Malawi','mw',-15.7863,35.0036,'city'],
    ['Bo','','Sierra Leone','sl',7.9621,-11.7366,'city'],
    ['Bobo-Dioulasso','','Burkina Faso','bf',11.1766,-4.2961,'city'],
    ['Bouaké','','Côte d\'Ivoire','ci',7.689,-5.0284,'city'],
    ['Brazzaville','','Republic of the Congo','cg',-4.2694,15.2712,'city'],
    ['Bubaque','','Guinea-Bissau','gw',11.3001,-15.8312,'city'],
    ['Buchanan','','Liberia','lr',5.8813,-10.0494,'city'],
    ['Budapest','Budapest','Hungary','hu',47.4979,19.0402,'city'],
    ['Buea','','Cameroon','cm',4.1568,9.2316,'city'],
    ['Buenos Aires','Buenos Aires','Argentina','ar',-34.6037,-58.3816,'city'],
    ['Bujumbura','','Burundi','bi',-3.3638,29.3675,'city'],
    ['Bukavu','','DR Congo','cd',-2.5056,28.8595,'city'],
    ['Bulawayo','','Zimbabwe','zw',-20.1054,28.5427,'city'],
    ['Cairo','','Egypt','eg',30.0444,31.2357,'city'],
    ['Calabar','','Nigeria','ng',4.9796,8.3374,'city'],
    ['Cape Coast','','Ghana','gh',5.1081,-1.2417,'city'],
    ['Cape Maclear','','Malawi','mw',-13.9987,34.853,'city'],
    ['Cape Town','','South Africa','za',-33.9288,18.4172,'city'],
    ['Cartagena','Cartagena','Colombia','co',10.391,-75.4794,'city'],
    ['Casablanca','','Morocco','ma',33.5945,-7.62,'city'],
    ['Chefchaouen','','Morocco','ma',35.1688,-5.2683,'city'],
    ['Chiang Mai','Chiang Mai','Thailand','th',18.7883,98.9853,'city'],
    ['Conakry','','Guinea','gn',9.5171,-13.6998,'city'],
    ['Constantine','','Algeria','dz',36.3642,6.6084,'city'],
    ['Copenhagen','Copenhagen','Denmark','dk',55.6761,12.5683,'city'],
    ['Cotonou','','Benin','bj',6.3677,2.4253,'city'],
    ['Dahab','','Egypt','eg',28.4964,34.5146,'city'],
    ['Dakar','','Senegal','sn',14.6934,-17.4479,'city'],
    ['Dar es Salaam','','Tanzania','tz',-6.8161,39.2804,'city'],
    ['Diani','','Kenya','ke',-4.3125,39.5794,'city'],
    ['Dire Dawa','','Ethiopia','et',9.5912,41.9797,'city'],
    ['Djerba','','Tunisia','tn',33.7736,10.8862,'city'],
    ['Dodoma','','Tanzania','tz',-6.1791,35.7468,'city'],
    ['Douala','','Cameroon','cm',4.0429,9.7062,'city'],
    ['Dubai','Dubai','United Arab Emirates','ae',25.2048,55.2708,'city'],
    ['Dubrovnik','Dubrovnik','Croatia','hr',42.6507,18.0944,'city'],
    ['Durban','','South Africa','za',-29.8618,31.0099,'city'],
    ['Edinburgh','Edinburgh','United Kingdom','gb',55.9533,-3.1883,'city'],
    ['Eldoret','','Kenya','ke',0.5198,35.2715,'city'],
    ['Elmina','','Ghana','gh',5.0859,-1.3506,'city'],
    ['Entebbe','','Uganda','ug',0.0612,32.4699,'city'],
    ['Enugu','','Nigeria','ng',6.5536,7.4143,'city'],
    ['Essaouira','','Morocco','ma',31.5118,-9.7621,'city'],
    ['Ezulwini','','Eswatini','sz',-26.4018,31.1783,'city'],
    ['Fes','','Morocco','ma',34.0347,-5.0162,'city'],
    ['Fianarantsoa','','Madagascar','mg',-21.4564,47.0851,'city'],
    ['Flic en Flac','','Mauritius','mu',-20.279,57.3691,'city'],
    ['Florence','Florence','Italy','it',43.7696,11.2558,'city'],
    ['Fort Portal','','Uganda','ug',0.6562,30.2779,'city'],
    ['Franceville','','Gabon','ga',-1.6344,13.5895,'city'],
    ['Francistown','','Botswana','bw',-21.1664,27.5025,'city'],
    ['Freetown','','Sierra Leone','sl',8.479,-13.268,'city'],
    ['Gaborone','','Botswana','bw',-24.6581,25.9088,'city'],
    ['Gisenyi','','Rwanda','rw',-1.6935,29.2599,'city'],
    ['Gitega','','Burundi','bi',-3.4285,29.925,'city'],
    ['Giza','','Egypt','eg',29.9871,31.2118,'city'],
    ['Goma','','DR Congo','cd',-1.6666,29.2257,'city'],
    ['Gondar','','Ethiopia','et',12.6104,37.4668,'city'],
    ['Grand Baie','','Mauritius','mu',-20.013,57.5846,'city'],
    ['Grand-Bassam','','Côte d\'Ivoire','ci',5.2129,-3.7432,'city'],
    ['Gulu','','Uganda','ug',3.0347,32.3802,'city'],
    ['Hammamet','','Tunisia','tn',36.4007,10.6191,'city'],
    ['Harare','','Zimbabwe','zw',-17.8567,31.0602,'city'],
    ['Hargeisa','','Somalia','so',9.5617,44.0618,'city'],
    ['Hawassa','','Ethiopia','et',7.0481,38.4786,'city'],
    ['Hermanus','','South Africa','za',-34.4175,19.2361,'city'],
    ['Ho','','Ghana','gh',6.6127,0.4689,'city'],
    ['Huambo','','Angola','ao',-12.7772,15.7347,'city'],
    ['Hurghada','','Egypt','eg',27.2226,33.8307,'city'],
    ['Huye','','Rwanda','rw',-2.6053,29.7402,'city'],
    ['Ibadan','','Nigeria','ng',7.3784,3.8972,'city'],
    ['Inhambane','','Mozambique','mz',-22.7791,34.5662,'city'],
    ['Istanbul','Istanbul','Türkiye','tr',41.0082,28.9784,'city'],
    ['Jinja','','Uganda','ug',0.5752,33.2805,'city'],
    ['Johannesburg','','South Africa','za',-26.205,28.0497,'city'],
    ['Juba','','South Sudan','ss',4.8459,31.5959,'city'],
    ['Kampala','','Uganda','ug',0.3177,32.5814,'city'],
    ['Kankan','','Guinea','gn',10.6248,-9.3175,'city'],
    ['Kano','','Nigeria','ng',11.994,8.522,'city'],
    ['Kasane','','Botswana','bw',-17.7992,25.1565,'city'],
    ['Kenema','','Sierra Leone','sl',7.886,-11.1864,'city'],
    ['Khartoum','','Sudan','sd',15.5636,32.5349,'city'],
    ['Kigali','','Rwanda','rw',-1.9534,30.114,'city'],
    ['Kinshasa','','DR Congo','cd',-4.3197,15.3424,'city'],
    ['Kisumu','','Kenya','ke',-0.1029,34.7542,'city'],
    ['Kitwe','','Zambia','zm',-12.8204,28.2156,'city'],
    ['Knysna','','South Africa','za',-34.0357,23.0485,'city'],
    ['Kololi','','Gambia','gm',13.4404,-16.7156,'city'],
    ['Kpalimé','','Togo','tg',6.9107,0.6324,'city'],
    ['Kribi','','Cameroon','cm',2.9434,9.9127,'city'],
    ['Kuala Lumpur','Kuala Lumpur','Malaysia','my',3.139,101.6869,'city'],
    ['Kumasi','','Ghana','gh',6.6986,-1.6233,'city'],
    ['Kyoto','Kyoto','Japan','jp',35.0116,135.7681,'city'],
    ['La Digue','','Seychelles','sc',-4.3601,55.8385,'city'],
    ['Labé','','Guinea','gn',11.7615,-12.0119,'city'],
    ['Lagos','','Nigeria','ng',6.4551,3.3942,'city'],
    ['Lalibela','','Ethiopia','et',12.0361,39.0457,'city'],
    ['Lamu','','Kenya','ke',-2.2675,40.901,'city'],
    ['Libreville','','Gabon','ga',0.4087,9.4419,'city'],
    ['Lilongwe','','Malawi','mw',-13.9875,33.7681,'city'],
    ['Limbe','','Cameroon','cm',4.0103,9.2071,'city'],
    ['Lisbon','Lisbon','Portugal','pt',38.7223,-9.1393,'city'],
    ['Lisbon & Porto','Lisbon','Portugal','pt',38.7223,-9.1393,'city'],
    ['Livingstone','','Zambia','zm',-17.8531,25.8614,'city'],
    ['Lomé','','Togo','tg',6.1304,1.2158,'city'],
    ['London','London','United Kingdom','gb',51.5074,-0.1278,'city'],
    ['Los Angeles','Los Angeles','United States','us',34.0522,-118.2437,'city'],
    ['Luanda','','Angola','ao',-8.8273,13.244,'city'],
    ['Lubango','','Angola','ao',-14.9196,13.4898,'city'],
    ['Lubumbashi','','DR Congo','cd',-11.6642,27.4826,'city'],
    ['Lusaka','','Zambia','zm',-15.4163,28.2818,'city'],
    ['Luxor','','Egypt','eg',25.7021,32.6472,'city'],
    ['Lüderitz','','Namibia','na',-26.65,15.1573,'city'],
    ['Madrid','Madrid','Spain','es',40.4168,-3.7038,'city'],
    ['Malabo','','Equatorial Guinea','gq',3.7419,8.7741,'city'],
    ['Malindi','','Kenya','ke',-3.2296,39.9751,'city'],
    ['Manzini','','Eswatini','sz',-26.4976,31.3751,'city'],
    ['Maputo','','Mozambique','mz',-25.9662,32.5675,'city'],
    ['Marrakech','','Morocco','ma',31.6258,-7.9892,'city'],
    ['Maseru','','Lesotho','ls',-29.3101,27.4782,'city'],
    ['Massawa','','Eritrea','er',15.6032,39.4637,'city'],
    ['Maun','','Botswana','bw',-19.9861,23.4224,'city'],
    ['Mbabane','','Eswatini','sz',-26.3257,31.1447,'city'],
    ['Mbarara','','Uganda','ug',-0.4181,30.5737,'city'],
    ['Medellín','Medellín','Colombia','co',6.2442,-75.5812,'city'],
    ['Mekelle','','Ethiopia','et',13.4967,39.4768,'city'],
    ['Melbourne','Melbourne','Australia','au',-37.8136,144.9631,'city'],
    ['Merzouga','','Morocco','ma',31.0999,-4.0141,'city'],
    ['Mexico City','Mexico City','Mexico','mx',19.4326,-99.1332,'city'],
    ['Miami','Miami','United States','us',25.7617,-80.1918,'city'],
    ['Milan','Milan','Italy','it',45.4642,9.19,'city'],
    ['Mindelo','','Cape Verde','cv',16.8873,-24.9864,'city'],
    ['Misrata','','Libya','ly',32.3746,15.0906,'city'],
    ['Mogadishu','','Somalia','so',2.0349,45.3419,'city'],
    ['Mombasa','','Kenya','ke',-4.0505,39.6672,'city'],
    ['Monrovia','','Liberia','lr',6.3204,-10.806,'city'],
    ['Mopti','','Mali','ml',14.5145,-3.6465,'city'],
    ['Morondava','','Madagascar','mg',-20.2951,44.2786,'city'],
    ['Moroni','','Comoros','km',-11.704,43.2519,'city'],
    ['Moshi','','Tanzania','tz',-3.3486,37.3435,'city'],
    ['Musanze','','Rwanda','rw',-1.5041,29.6363,'city'],
    ['Mutare','','Zimbabwe','zw',-18.9747,32.6705,'city'],
    ['Mutsamudu','','Comoros','km',-12.1688,44.3943,'city'],
    ['Mwanza','','Tanzania','tz',-2.5197,32.9014,'city'],
    ['Mzuzu','','Malawi','mw',-11.4608,34.0226,'city'],
    ['N\'Djamena','','Chad','td',12.1192,15.0503,'city'],
    ['Nairobi','','Kenya','ke',-1.3024,36.8289,'city'],
    ['Naivasha','','Kenya','ke',-0.7224,36.4388,'city'],
    ['Nakuru','','Kenya','ke',-0.2803,36.0712,'city'],
    ['Nanyuki','','Kenya','ke',0.014,37.0746,'city'],
    ['Ndola','','Zambia','zm',-12.9693,28.6366,'city'],
    ['New York','New York','United States','us',40.7128,-74.006,'city'],
    ['Niamey','','Niger','ne',13.5248,2.1098,'city'],
    ['Nkhata Bay','','Malawi','mw',-11.6084,34.0416,'city'],
    ['Nosy Be','','Madagascar','mg',-13.312,48.2534,'city'],
    ['Nouadhibou','','Mauritania','mr',20.9127,-17.0503,'city'],
    ['Nouakchott','','Mauritania','mr',18.0792,-15.978,'city'],
    ['Omdurman','','Sudan','sd',15.6446,32.4777,'city'],
    ['Oran','','Algeria','dz',35.7044,-0.6503,'city'],
    ['Ouagadougou','','Burkina Faso','bf',12.3682,-1.5271,'city'],
    ['Ouidah','','Benin','bj',6.3666,2.0854,'city'],
    ['Parakou','','Benin','bj',9.34,2.6278,'city'],
    ['Paris','Paris','France','fr',48.8566,2.3522,'city'],
    ['Pemba','','Mozambique','mz',-12.9736,40.5215,'city'],
    ['Phuket','Phuket','Thailand','th',7.8804,98.3923,'city'],
    ['Pointe-Noire','','Republic of the Congo','cg',-4.7975,11.8503,'city'],
    ['Port Elizabeth','','South Africa','za',-33.9619,25.6187,'city'],
    ['Port Harcourt','','Nigeria','ng',4.7677,7.0189,'city'],
    ['Port Louis','','Mauritius','mu',-20.1625,57.5028,'city'],
    ['Port Sudan','','Sudan','sd',19.6192,37.2117,'city'],
    ['Port-Gentil','','Gabon','ga',-0.7152,8.7788,'city'],
    ['Porto-Novo','','Benin','bj',6.4991,2.6253,'city'],
    ['Prague','Prague','Czechia','cz',50.0755,14.4378,'city'],
    ['Praia','','Cape Verde','cv',14.9163,-23.5095,'city'],
    ['Praslin','','Seychelles','sc',-4.3251,55.7356,'city'],
    ['Pretoria','','South Africa','za',-25.7459,28.1879,'city'],
    ['Rabat','','Morocco','ma',34.0218,-6.8409,'city'],
    ['Rio de Janeiro','Rio de Janeiro','Brazil','br',-22.9068,-43.1729,'city'],
    ['Robertsport','','Liberia','lr',6.7526,-11.367,'city'],
    ['Rome','Rome','Italy','it',41.9028,12.4964,'city'],
    ['Rubavu','','Rwanda','rw',-1.6417,29.3336,'city'],
    ['Saint-Louis','','Senegal','sn',16.028,-16.5049,'city'],
    ['Sal Rei','','Cape Verde','cv',16.176,-22.917,'city'],
    ['Saly','','Senegal','sn',14.4411,-17.0148,'city'],
    ['San-Pédro','','Côte d\'Ivoire','ci',4.759,-6.6464,'city'],
    ['Santa Maria','','Cape Verde','cv',16.5987,-22.905,'city'],
    ['Santo António','','São Tomé and Príncipe','st',1.6382,7.4198,'city'],
    ['Santorini','Santorini','Greece','gr',36.3932,25.4615,'city'],
    ['Semonkong','','Lesotho','ls',-29.84,28.0511,'city'],
    ['Seoul','Seoul','South Korea','kr',37.5665,126.978,'city'],
    ['Serrekunda','','Gambia','gm',13.4388,-16.6748,'city'],
    ['Sfax','','Tunisia','tn',34.7394,10.7604,'city'],
    ['Sharm El Sheikh','','Egypt','eg',27.8644,34.2954,'city'],
    ['Singapore','Singapore','Singapore','sg',1.3521,103.8198,'city'],
    ['Sokodé','','Togo','tg',8.9874,1.1358,'city'],
    ['Sousse','','Tunisia','tn',35.8288,10.6405,'city'],
    ['Stellenbosch','','South Africa','za',-33.9344,18.8692,'city'],
    ['Stone Town','','Tanzania','tz',-6.1627,39.1897,'city'],
    ['Swakopmund','','Namibia','na',-22.6768,14.529,'city'],
    ['Sydney','Sydney','Australia','au',-33.8688,151.2093,'city'],
    ['São Tomé','','São Tomé and Príncipe','st',0.3389,6.7313,'city'],
    ['Ségou','','Mali','ml',13.4415,-6.2681,'city'],
    ['Tadjoura','','Djibouti','dj',11.7857,42.8847,'city'],
    ['Takoradi','','Ghana','gh',4.8874,-1.7519,'city'],
    ['Tamale','','Ghana','gh',9.4052,-0.8424,'city'],
    ['Tamanrasset','','Algeria','dz',24.3753,4.3208,'city'],
    ['Tangier','','Morocco','ma',35.7696,-5.8034,'city'],
    ['Thika','','Kenya','ke',-1.0366,37.0775,'city'],
    ['Thiès','','Senegal','sn',14.7915,-16.9256,'city'],
    ['Toamasina','','Madagascar','mg',-18.1554,49.4098,'city'],
    ['Tofo','','Mozambique','mz',-23.8536,35.5472,'city'],
    ['Tokyo','Tokyo','Japan','jp',35.6762,139.6503,'city'],
    ['Tripoli','','Libya','ly',32.8967,13.1778,'city'],
    ['Tunis','','Tunisia','tn',36.8002,10.1858,'city'],
    ['Victoria','','Seychelles','sc',-4.6232,55.4524,'city'],
    ['Victoria Falls','','Zimbabwe','zw',-17.9229,25.8477,'city'],
    ['Vienna','Vienna','Austria','at',48.2082,16.3738,'city'],
    ['Vilanculos','','Mozambique','mz',-21.999,35.3205,'city'],
    ['Walvis Bay','','Namibia','na',-22.9558,14.5071,'city'],
    ['Watamu','','Kenya','ke',-3.35,40.0166,'city'],
    ['Windhoek','','Namibia','na',-22.5776,17.0773,'city'],
    ['Yamoussoukro','','Côte d\'Ivoire','ci',6.82,-5.2776,'city'],
    ['Yaoundé','','Cameroon','cm',3.869,11.5213,'city'],
    ['Zanzibar','Zanzibar City','Tanzania','tz',-6.1659,39.2026,'city'],
    ['Zanzibar City','','Tanzania','tz',-6.1665,39.2074,'city'],
    ['Ziguinchor','','Senegal','sn',12.5635,-16.2725,'city'],
    ['Airport Residential','Accra','Ghana','gh',5.605,-0.178,'neighbourhood'],
    ['Bamburi','Mombasa','Kenya','ke',-3.99,39.72,'neighbourhood'],
    ['East Legon','Accra','Ghana','gh',5.635,-0.156,'neighbourhood'],
    ['Gigiri','Nairobi','Kenya','ke',-1.235,36.8039,'neighbourhood'],
    ['Ikeja','Lagos','Nigeria','ng',6.6018,3.3515,'neighbourhood'],
    ['Ikoyi','Lagos','Nigeria','ng',6.455,3.435,'neighbourhood'],
    ['Karen','Nairobi','Kenya','ke',-1.3197,36.7076,'neighbourhood'],
    ['Kileleshwa','Nairobi','Kenya','ke',-1.2807,36.7789,'neighbourhood'],
    ['Kilimani','Nairobi','Kenya','ke',-1.2921,36.7833,'neighbourhood'],
    ['Lavington','Nairobi','Kenya','ke',-1.2795,36.7686,'neighbourhood'],
    ['Lekki','Lagos','Nigeria','ng',6.4698,3.5852,'neighbourhood'],
    ['Muthaiga','Nairobi','Kenya','ke',-1.25,36.83,'neighbourhood'],
    ['Nairobi CBD','Nairobi','Kenya','ke',-1.2864,36.8172,'neighbourhood'],
    ['Ngong Road','Nairobi','Kenya','ke',-1.3,36.76,'neighbourhood'],
    ['Nyali','Mombasa','Kenya','ke',-4.03,39.7,'neighbourhood'],
    ['Ongata Rongai','Nairobi','Kenya','ke',-1.3961,36.7447,'neighbourhood'],
    ['Parklands','Nairobi','Kenya','ke',-1.2603,36.8189,'neighbourhood'],
    ['Runda','Nairobi','Kenya','ke',-1.217,36.81,'neighbourhood'],
    ['South C','Nairobi','Kenya','ke',-1.3225,36.83,'neighbourhood'],
    ['Syokimau','Nairobi','Kenya','ke',-1.3667,36.9333,'neighbourhood'],
    ['Thika Road','Nairobi','Kenya','ke',-1.22,36.89,'neighbourhood'],
    ['Upper Hill','Nairobi','Kenya','ke',-1.2996,36.8148,'neighbourhood'],
    ['Victoria Island','Lagos','Nigeria','ng',6.4281,3.4219,'neighbourhood'],
    ['Westlands','Nairobi','Kenya','ke',-1.2676,36.8108,'neighbourhood'],
    ['Abeid Amani Karume International Airport','Zanzibar','Tanzania','tz',-6.222,39.2249,'airport'],
    ['Bole International Airport','Addis Ababa','Ethiopia','et',8.9779,38.7993,'airport'],
    ['Cairo International Airport','Cairo','Egypt','eg',30.1219,31.4056,'airport'],
    ['Cape Town International Airport','Cape Town','South Africa','za',-33.9715,18.6021,'airport'],
    ['Dubai International Airport','Dubai','United Arab Emirates','ae',25.2532,55.3657,'airport'],
    ['Entebbe International Airport','Kampala','Uganda','ug',0.0424,32.4435,'airport'],
    ['Jomo Kenyatta International Airport','Nairobi','Kenya','ke',-1.3192,36.9278,'airport'],
    ['Julius Nyerere International Airport','Dar es Salaam','Tanzania','tz',-6.8781,39.2026,'airport'],
    ['Kigali International Airport','Kigali','Rwanda','rw',-1.9686,30.1395,'airport'],
    ['Kilimanjaro International Airport','Arusha','Tanzania','tz',-3.4294,37.0745,'airport'],
    ['Kotoka International Airport','Accra','Ghana','gh',5.6052,-0.1668,'airport'],
    ['Mohammed V International Airport','Casablanca','Morocco','ma',33.3675,-7.5899,'airport'],
    ['Moi International Airport','Mombasa','Kenya','ke',-4.0348,39.5942,'airport'],
    ['Murtala Muhammed International Airport','Lagos','Nigeria','ng',6.5774,3.3212,'airport'],
    ['O. R. Tambo International Airport','Johannesburg','South Africa','za',-26.1367,28.2411,'airport'],
    ['Wilson Airport','Nairobi','Kenya','ke',-1.3218,36.8148,'airport'],
    ['Nairobi Terminus (SGR)','Nairobi','Kenya','ke',-1.381,36.916,'transport'],
    ['Diani Beach','Diani','Kenya','ke',-4.2767,39.593,'poi'],
    ['Masai Mara','Narok','Kenya','ke',-1.4061,35.008,'region'],
    ['Ngorongoro','Arusha','Tanzania','tz',-3.2,35.5,'region'],
    ['Serengeti','Arusha','Tanzania','tz',-2.3333,34.8333,'region'],
    ['Algeria','','Algeria','dz',36.7538,3.0588,'country'],
    ['Angola','','Angola','ao',-8.839,13.2894,'country'],
    ['Benin','','Benin','bj',6.3703,2.3912,'country'],
    ['Botswana','','Botswana','bw',-24.6282,25.9231,'country'],
    ['Burkina Faso','','Burkina Faso','bf',12.3714,-1.5197,'country'],
    ['Burundi','','Burundi','bi',-3.3822,29.3644,'country'],
    ['Cameroon','','Cameroon','cm',4.0511,9.7679,'country'],
    ['Cape Verde','','Cape Verde','cv',14.9331,-23.5133,'country'],
    ['Central African Republic','','Central African Republic','cf',4.3947,18.5582,'country'],
    ['Chad','','Chad','td',12.1348,15.0557,'country'],
    ['Comoros','','Comoros','km',-11.7172,43.2473,'country'],
    ['Côte d\'Ivoire','','Côte d\'Ivoire','ci',5.36,-4.0083,'country'],
    ['DR Congo','','DR Congo','cd',-4.4419,15.2663,'country'],
    ['Djibouti','','Djibouti','dj',11.5721,43.1456,'country'],
    ['Egypt','','Egypt','eg',30.0444,31.2357,'country'],
    ['Equatorial Guinea','','Equatorial Guinea','gq',3.7523,8.7742,'country'],
    ['Eritrea','','Eritrea','er',15.3229,38.9251,'country'],
    ['Eswatini','','Eswatini','sz',-26.3054,31.1367,'country'],
    ['Ethiopia','','Ethiopia','et',9.032,38.7469,'country'],
    ['Gabon','','Gabon','ga',0.4162,9.4673,'country'],
    ['Gambia','','Gambia','gm',13.4432,-16.6137,'country'],
    ['Ghana','','Ghana','gh',5.6037,-0.187,'country'],
    ['Guinea','','Guinea','gn',9.6412,-13.5784,'country'],
    ['Guinea-Bissau','','Guinea-Bissau','gw',11.8817,-15.6178,'country'],
    ['Kenya','','Kenya','ke',-1.2921,36.8219,'country'],
    ['Lesotho','','Lesotho','ls',-29.3151,27.4869,'country'],
    ['Liberia','','Liberia','lr',6.2907,-10.7605,'country'],
    ['Libya','','Libya','ly',32.8872,13.1913,'country'],
    ['Madagascar','','Madagascar','mg',-18.8792,47.5079,'country'],
    ['Malawi','','Malawi','mw',-13.9626,33.7741,'country'],
    ['Mali','','Mali','ml',12.6392,-8.0029,'country'],
    ['Mauritania','','Mauritania','mr',18.0735,-15.9582,'country'],
    ['Mauritius','','Mauritius','mu',-20.1609,57.5012,'country'],
    ['Morocco','','Morocco','ma',33.5731,-7.5898,'country'],
    ['Mozambique','','Mozambique','mz',-25.9692,32.5732,'country'],
    ['Namibia','','Namibia','na',-22.5609,17.0658,'country'],
    ['Niger','','Niger','ne',13.5116,2.1254,'country'],
    ['Nigeria','','Nigeria','ng',6.5244,3.3792,'country'],
    ['Republic of the Congo','','Republic of the Congo','cg',-4.2634,15.2429,'country'],
    ['Rwanda','','Rwanda','rw',-1.9441,30.0619,'country'],
    ['Senegal','','Senegal','sn',14.7167,-17.4677,'country'],
    ['Seychelles','','Seychelles','sc',-4.6796,55.492,'country'],
    ['Sierra Leone','','Sierra Leone','sl',8.4657,-13.2317,'country'],
    ['Somalia','','Somalia','so',2.0469,45.3182,'country'],
    ['South Africa','','South Africa','za',-26.2041,28.0473,'country'],
    ['South Sudan','','South Sudan','ss',4.8594,31.5713,'country'],
    ['Sudan','','Sudan','sd',15.5007,32.5599,'country'],
    ['São Tomé and Príncipe','','São Tomé and Príncipe','st',0.3302,6.7333,'country'],
    ['Tanzania','','Tanzania','tz',-6.7924,39.2083,'country'],
    ['Togo','','Togo','tg',6.1725,1.2314,'country'],
    ['Tunisia','','Tunisia','tn',36.8065,10.1815,'country'],
    ['Uganda','','Uganda','ug',0.3476,32.5825,'country'],
    ['Zambia','','Zambia','zm',-15.3875,28.3228,'country'],
    ['Zimbabwe','','Zimbabwe','zw',-17.8252,31.0335,'country']
  ];
  /* GAZETTEER:END */

  /* Aliases the gazetteer cannot carry: what people type versus what
     the place is called. Kept by hand because it is knowledge about
     travellers, not about geography. */
  var ALIASES = {
    'jkia': 'Jomo Kenyatta International Airport',
    'nbo': 'Jomo Kenyatta International Airport',
    'town': 'Nairobi CBD',
    'city centre': 'Nairobi CBD',
    'city center': 'Nairobi CBD',
    'mara': 'Masai Mara',
    'maasai mara': 'Masai Mara',
    'coast': 'Mombasa',
    'ukunda': 'Diani Beach',
    'stone town': 'Zanzibar',
    'nyc': 'New York',
    'uae': 'Dubai'
  };

  /* Comparison form. Accents are stripped rather than respected on
     purpose: a guest types "medellin" and means Medellín, and a host
     types "Zurich" and means Zürich. Matching has to survive a keyboard
     that cannot produce the character the place is spelled with. */
  function norm(s) {
    var t = String(s == null ? '' : s).toLowerCase();
    if (t.normalize) t = t.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    return t.replace(/[^a-z0-9 ]+/g, ' ').replace(/\s+/g, ' ').trim();
  }

  var _seedIndex = null;

  function seedIndex() {
    if (_seedIndex) return _seedIndex;
    _seedIndex = SEED.map(function (row, i) {
      return {
        i: i,
        name: row[0],
        parent: row[1],
        country: row[2],
        cc: row[3],
        lat: row[4],
        lng: row[5],
        kind: row[6],
        n: norm(row[0]),
        hay: norm([row[0], row[1], row[2]].join(' '))
      };
    });
    return _seedIndex;
  }

  /* Instant, offline, zero-latency. Deliberately generous about what
     counts as a match — this is the layer that keeps the dropdown from
     ever being empty, and the network layer that follows it is the one
     that is precise. */
  function searchSeed(q, limit) {
    var query = norm(q);
    if (!query) return [];
    if (ALIASES[query]) query = norm(ALIASES[query]);

    var out = [];
    var idx = seedIndex();

    for (var i = 0; i < idx.length; i++) {
      var e = idx[i];
      var s = -1;
      if (e.n === query) s = 0;
      else if (e.n.indexOf(query) === 0) s = 1;
      else if (e.hay.indexOf(query) === 0) s = 2;
      else if (e.n.indexOf(query) > -1) s = 3;
      else if (e.hay.indexOf(query) > -1) s = 4;
      if (s < 0) continue;
      /* Cities outrank neighbourhoods at equal textual quality: someone
         typing three letters usually means the big thing. */
      var rank = s * 10 + (e.kind === 'city' ? 0 : e.kind === 'neighbourhood' ? 1 : 2);
      out.push({ e: e, r: rank });
    }

    out.sort(function (a, b) { return a.r - b.r; });

    return out.slice(0, limit || 6).map(function (o) {
      var e = o.e;
      return place({
        id: 'seed:' + e.i,
        name: e.name,
        label: [e.name, e.parent, e.country].filter(uniqTruthy()).join(', '),
        lat: e.lat,
        lng: e.lng,
        kind: e.kind,
        city: e.kind === 'city' ? e.name : e.parent,
        country: e.country,
        countryCode: e.cc,
        source: 'cabana'
      });
    });
  }

  /* Small helper for the join above: drops empties *and* repeats, so
     "Nairobi, Nairobi, Kenya" never reaches a human. */
  function uniqTruthy() {
    var seen = {};
    return function (v) {
      if (!v) return false;
      var k = String(v).toLowerCase();
      if (seen[k]) return false;
      seen[k] = 1;
      return true;
    };
  }

  /* ════════════════════════════════════════════════════════════════
     2 · THE RECORD

     One shape, whatever answered. Every caller in the codebase reads
     these fields and no others, which is what makes the provider
     behind them swappable.
     ════════════════════════════════════════════════════════════════ */

  function place(o) {
    var name = str(o.name);
    var label = str(o.label) || name;
    return {
      id: o.id || ('pt:' + o.lat + ',' + o.lng),
      name: name,
      label: label,
      short: str(o.short) || shortOf(o, label),
      lat: Number(o.lat),
      lng: Number(o.lng),
      kind: o.kind || 'place',
      street: str(o.street),
      area: str(o.area),
      city: str(o.city),
      state: str(o.state),
      country: str(o.country),
      countryCode: str(o.countryCode).toLowerCase(),
      postcode: str(o.postcode),
      bbox: Array.isArray(o.bbox) && o.bbox.length === 4 ? o.bbox : null,
      score: Number(o.score) || 0,
      distanceKm: typeof o.distanceKm === 'number' ? o.distanceKm : null,
      source: o.source || 'unknown'
    };
  }

  function str(v) { return String(v == null ? '' : v).replace(/\s+/g, ' ').trim(); }

  function shortOf(o, label) {
    var parts = [o.name, o.area || o.street, o.city, o.country].filter(uniqTruthy());
    return parts.slice(0, 3).join(', ') ||
           String(label).split(',').slice(0, 3).map(function (s) { return s.trim(); }).join(', ');
  }

  /* ════════════════════════════════════════════════════════════════
     3 · CACHE, BIAS, RECENTS
     ════════════════════════════════════════════════════════════════ */

  var mem = {};

  function ssGet(k) {
    try { var raw = sessionStorage.getItem(k); return raw ? JSON.parse(raw) : null; }
    catch (e) { return null; }
  }
  function ssSet(k, v) { try { sessionStorage.setItem(k, JSON.stringify(v)); } catch (e) {} }
  function lsGet(k) {
    try { var raw = localStorage.getItem(k); return raw ? JSON.parse(raw) : null; }
    catch (e) { return null; }
  }
  function lsSet(k, v) { try { localStorage.setItem(k, JSON.stringify(v)); } catch (e) {} }

  /* Where to weight results toward. Set by the last place the user
     picked, or by their device fix — never by an IP guess, which is
     wrong often enough to be infuriating when it is. */
  function getBias() {
    var b = lsGet(BIAS_KEY);
    return b && isFinite(b.lat) && isFinite(b.lng) ? b : null;
  }

  function setBias(p) {
    if (!p || !isFinite(p.lat) || !isFinite(p.lng)) return;
    lsSet(BIAS_KEY, { lat: p.lat, lng: p.lng, label: p.short || p.label || '', at: Date.now() });
  }

  function recents() {
    var r = lsGet(RECENT_KEY);
    return Array.isArray(r) ? r.filter(function (p) { return p && isFinite(p.lat); }) : [];
  }

  function remember(p) {
    if (!p || !isFinite(p.lat)) return;
    var list = recents().filter(function (x) {
      return !(Math.abs(x.lat - p.lat) < 1e-5 && Math.abs(x.lng - p.lng) < 1e-5);
    });
    list.unshift(p);
    lsSet(RECENT_KEY, list.slice(0, RECENT_MAX));
    setBias(p);
  }

  /* ════════════════════════════════════════════════════════════════
     4 · SEARCH
     ════════════════════════════════════════════════════════════════ */

  var apiAlive = true;   // flips false after a hard failure, so we stop knocking
  var inflight = {};     // query key → promise, so ten keystrokes are one call

  /* Forward search.

       o.limit    how many (default 8)
       o.near     {lat,lng} to bias toward; defaults to the stored bias
       o.country  ISO2 or array, when a form is genuinely single-country
       o.lang     response language (default the document's)
       o.seed     merge instant gazetteer hits (default true)
       o.signal   AbortSignal

     Resolves to [] rather than rejecting. A search box is not the place
     to surface a network error as an exception. */
  function search(q, o) {
    o = o || {};
    q = str(q);
    if (q.length < MIN_CHARS) return Promise.resolve([]);

    var limit = o.limit || 8;
    var near = o.near || (o.bias === false ? null : getBias());
    var country = o.country
      ? (Array.isArray(o.country) ? o.country : String(o.country).split(','))
          .map(function (c) { return str(c).toLowerCase(); }).filter(function (c) { return c.length === 2; })
      : null;

    var key = 'g:' + q.toLowerCase() + '|' + limit + '|' + (country ? country.join('+') : '*') +
              '|' + (near ? near.lat.toFixed(1) + ',' + near.lng.toFixed(1) : '-');

    var local = o.seed === false ? [] : searchSeed(q, Math.min(limit, 5));

    if (mem[key]) return Promise.resolve(merge(local, mem[key], limit));
    var stored = ssGet(key);
    if (stored) { mem[key] = stored; return Promise.resolve(merge(local, stored, limit)); }
    if (inflight[key]) return inflight[key].then(function (r) { return merge(local, r, limit); });

    var run = remote(q, { limit: limit, near: near, country: country, lang: o.lang, signal: o.signal })
      .then(function (rows) {
        if (rows.length) { mem[key] = rows; ssSet(key, rows); }
        return rows;
      })
      .catch(function () { return []; })
      .then(function (rows) { delete inflight[key]; return rows; });

    inflight[key] = run;
    return run.then(function (rows) { return merge(local, rows, limit); });
  }

  /* Gazetteer hits lead — they are Cabana's own inventory areas and a
     guest searching them should land on the canonical record, not on
     whichever OSM node happens to share the name. Remote results fill
     the rest and are deduped against what is already shown. */
  function merge(local, remoteRows, limit) {
    var out = [];
    var seen = {};

    function push(p) {
      if (!p || !isFinite(p.lat) || !isFinite(p.lng)) return;
      var k = norm(p.name) + '|' + p.lat.toFixed(2) + '|' + p.lng.toFixed(2);
      if (seen[k]) return;
      seen[k] = 1;
      out.push(p);
    }

    local.forEach(push);
    (remoteRows || []).forEach(push);
    return out.slice(0, limit);
  }

  function remote(q, o) {
    if (!apiAlive) return direct(q, o);

    var u = API + '?q=' + encodeURIComponent(q) + '&limit=' + (o.limit || 8) +
            '&lang=' + encodeURIComponent(o.lang || docLang());
    if (o.near) u += '&near=' + o.near.lat.toFixed(4) + ',' + o.near.lng.toFixed(4);
    if (o.country && o.country.length) u += '&country=' + o.country.join(',');

    return fetch(u, { signal: o.signal })
      .then(function (r) {
        /* A 404 means this deploy has no geocode route at all — stop
           asking for the rest of the session and use the open providers
           straight away, rather than paying a failed round trip per
           keystroke forever. */
        if (r.status === 404) { apiAlive = false; throw new Error('no route'); }
        if (!r.ok) throw new Error('geocode ' + r.status);
        return r.json();
      })
      .then(function (data) { return (data.results || []).map(place); })
      .catch(function (e) {
        if (e && e.name === 'AbortError') throw e;
        return direct(q, o);
      });
  }

  /* Last resort: talk to the open providers from the browser. */
  function direct(q, o) {
    var u = PHOTON + '?q=' + encodeURIComponent(q) + '&limit=' + (o.limit || 8) + '&lang=en';
    if (o.near) u += '&lat=' + o.near.lat.toFixed(4) + '&lon=' + o.near.lng.toFixed(4);

    return fetch(u, { signal: o.signal })
      .then(function (r) { return r.ok ? r.json() : { features: [] }; })
      .then(function (d) {
        var rows = (d.features || []).map(fromPhoton).filter(Boolean);
        if (rows.length) return rows;
        return directOSM(q, o);
      })
      .catch(function (e) {
        if (e && e.name === 'AbortError') throw e;
        return directOSM(q, o);
      });
  }

  function directOSM(q, o) {
    var u = NOMINATIM + '?format=jsonv2&addressdetails=1&limit=' + (o.limit || 8) +
            '&q=' + encodeURIComponent(q);
    return fetch(u, { signal: o.signal, headers: { 'Accept-Language': 'en' } })
      .then(function (r) { return r.ok ? r.json() : []; })
      .then(function (rows) { return (rows || []).map(fromOSM).filter(Boolean); })
      .catch(function () { return []; });
  }

  function fromPhoton(f) {
    var p = f.properties || {}, g = f.geometry || {};
    var lng = Number(g.coordinates && g.coordinates[0]);
    var lat = Number(g.coordinates && g.coordinates[1]);
    if (!isFinite(lat) || !isFinite(lng)) return null;
    var name = str(p.name) || str(p.street) || str(p.city) || str(p.country);
    return place({
      id: 'photon:' + (p.osm_id || lat + ',' + lng),
      name: name,
      label: [p.housenumber ? p.housenumber + ' ' + (p.street || '') : p.street,
              name, p.district, p.city, p.state, p.country].filter(uniqTruthy()).join(', '),
      lat: lat, lng: lng,
      kind: kindOf(p.osm_value, p.osm_key),
      street: p.street, area: p.district, city: p.city || p.county,
      state: p.state, country: p.country, countryCode: p.countrycode,
      postcode: p.postcode, source: 'photon'
    });
  }

  function fromOSM(r) {
    var lat = Number(r.lat), lng = Number(r.lon);
    if (!isFinite(lat) || !isFinite(lng)) return null;
    var a = r.address || {};
    var street = a.road || a.pedestrian || '';
    return place({
      id: 'osm:' + (r.osm_id || lat + ',' + lng),
      name: str(r.name) || street || a.suburb || a.city || String(r.display_name || '').split(',')[0],
      label: r.display_name,
      lat: lat, lng: lng,
      kind: kindOf(r.type, r.class),
      street: street, area: a.suburb || a.neighbourhood,
      city: a.city || a.town || a.village || a.county,
      state: a.state, country: a.country, countryCode: a.country_code,
      postcode: a.postcode, source: 'nominatim'
    });
  }

  /* The browser-side mirror of the server's kind mapping. Short, because
     only the fallback path reaches it. */
  var KINDS = {
    aerodrome: 'airport', airport: 'airport',
    city: 'city', town: 'city', village: 'city', municipality: 'city',
    suburb: 'neighbourhood', neighbourhood: 'neighbourhood', quarter: 'neighbourhood',
    residential: 'street', road: 'street', house: 'address', building: 'address',
    hotel: 'poi', mall: 'poi', attraction: 'poi', beach: 'poi',
    state: 'region', county: 'region', country: 'country'
  };
  function kindOf(a, b) { return KINDS[String(a).toLowerCase()] || KINDS[String(b).toLowerCase()] || 'place'; }

  function docLang() {
    return (document.documentElement.getAttribute('lang') || 'en').slice(0, 2).toLowerCase();
  }

  /* ── Reverse ──────────────────────────────────────────────────── */

  function reverse(lat, lng) {
    lat = Number(lat); lng = Number(lng);
    if (!isFinite(lat) || !isFinite(lng)) return Promise.resolve(null);

    var key = 'gr:' + lat.toFixed(4) + ',' + lng.toFixed(4);
    if (mem[key]) return Promise.resolve(mem[key]);
    var stored = ssGet(key);
    if (stored) { mem[key] = stored; return Promise.resolve(stored); }

    var u = apiAlive
      ? API + '?lat=' + lat + '&lng=' + lng + '&lang=' + docLang()
      : 'https://photon.komoot.io/reverse?lat=' + lat + '&lon=' + lng + '&lang=en';

    return fetch(u)
      .then(function (r) {
        if (r.status === 404) { apiAlive = false; throw new Error('no route'); }
        return r.ok ? r.json() : null;
      })
      .then(function (d) {
        if (!d) return null;
        var row = d.results ? d.results[0] : (d.features || [])[0];
        if (!row) return null;
        var p = d.results ? place(row) : fromPhoton(row);
        if (p) { mem[key] = p; ssSet(key, p); }
        return p;
      })
      .catch(function () {
        /* A pin without a label is still a pin. Callers treat the label
           as decoration precisely so this can fail quietly. */
        return null;
      });
  }

  /* ── The device's own fix ─────────────────────────────────────── */

  function locate(o) {
    o = o || {};
    return new Promise(function (res, rej) {
      if (!navigator.geolocation) return rej(new Error('This device cannot share a location'));
      navigator.geolocation.getCurrentPosition(function (pos) {
        var lat = pos.coords.latitude, lng = pos.coords.longitude;
        reverse(lat, lng).then(function (p) {
          var out = p || place({ name: 'Current location', lat: lat, lng: lng, kind: 'poi', source: 'device' });
          /* Keep the true fix. The reverse geocode names the street; it
             must not move the point to the middle of it. */
          out.lat = lat; out.lng = lng;
          out.accuracy = pos.coords.accuracy || null;
          out.source = 'device';
          setBias(out);
          res(out);
        });
      }, function (err) {
        rej(new Error(
          err.code === 1 ? 'Location permission was declined — type the place instead'
                         : 'Could not read your location — type the place instead'
        ));
      }, {
        enableHighAccuracy: o.highAccuracy !== false,
        timeout: o.timeout || 12000,
        maximumAge: o.maximumAge != null ? o.maximumAge : 60000
      });
    });
  }

  /* ════════════════════════════════════════════════════════════════
     5 · GEOMETRY

     What makes a search a search rather than a string comparison.
     ════════════════════════════════════════════════════════════════ */

  function distance(a, b) {
    if (!a || !b) return Infinity;
    var lat1 = Number(a.lat), lng1 = Number(a.lng), lat2 = Number(b.lat), lng2 = Number(b.lng);
    if (!isFinite(lat1) || !isFinite(lng1) || !isFinite(lat2) || !isFinite(lng2)) return Infinity;
    var R = 6371, p = Math.PI / 180;
    var dLat = (lat2 - lat1) * p, dLng = (lng2 - lng1) * p;
    var s = Math.sin(dLat / 2) * Math.sin(dLat / 2) +
            Math.cos(lat1 * p) * Math.cos(lat2 * p) * Math.sin(dLng / 2) * Math.sin(dLng / 2);
    return 2 * R * Math.atan2(Math.sqrt(s), Math.sqrt(1 - s));
  }

  /* A sensible first radius for what was searched. Someone who typed a
     street means the street; someone who typed a country means the
     country, and offering them a 5km circle around its centroid would
     be absurd. */
  function radiusFor(p, fallback) {
    if (!p) return fallback || 25;
    if (p.bbox) {
      /* Half the diagonal of the place's own extent is the honest
         radius — it is the geocoder's own statement of how big the
         thing is, rather than our guess about what its name implies. */
      var d = distance({ lat: p.bbox[0], lng: p.bbox[1] }, { lat: p.bbox[2], lng: p.bbox[3] }) / 2;
      if (isFinite(d) && d > 0.5) return Math.min(d, 400);
    }
    return ({
      address: 3, street: 3, poi: 5, airport: 12, transport: 8,
      neighbourhood: 6, city: 30, postcode: 8, region: 120, country: 500
    })[p.kind] || fallback || 25;
  }

  /* Filter a list to what is near a point, annotate each with its
     distance, and — this is the part that matters — widen the circle
     rather than return nothing.

       o.radiusKm  starting radius (default: derived from the place)
       o.expand    rings to try before giving up
       o.min       keep widening until at least this many are found
       o.latKey / o.lngKey   field names on the items */
  function nearby(items, centre, o) {
    o = o || {};
    if (!centre || !isFinite(centre.lat) || !isFinite(centre.lng)) {
      return { items: [], radiusKm: 0, expanded: false, exact: false };
    }

    var latKey = o.latKey || 'lat';
    var lngKey = o.lngKey || 'lng';
    var min = o.min == null ? 1 : o.min;
    var base = o.radiusKm || radiusFor(centre, 25);
    var rings = o.expand || [base, base * 2.5, base * 6, base * 15, base * 40];

    var withDist = [];
    for (var i = 0; i < items.length; i++) {
      var it = items[i];
      var lat = Number(it[latKey]), lng = Number(it[lngKey]);
      if (!isFinite(lat) || !isFinite(lng)) continue;
      withDist.push({ item: it, km: distance(centre, { lat: lat, lng: lng }) });
    }
    withDist.sort(function (a, b) { return a.km - b.km; });

    for (var r = 0; r < rings.length; r++) {
      var radius = Math.min(rings[r], 20000);
      var hit = withDist.filter(function (x) { return x.km <= radius; });
      if (hit.length >= min || r === rings.length - 1) {
        return {
          items: hit.map(function (x) { x.item.distanceKm = Math.round(x.km * 10) / 10; return x.item; }),
          radiusKm: Math.round(radius),
          expanded: r > 0,
          exact: r === 0,
          /* Everything with coordinates, nearest first, for a caller
             that would rather show the closest five than nothing. */
          all: withDist.map(function (x) { x.item.distanceKm = Math.round(x.km * 10) / 10; return x.item; })
        };
      }
    }

    return { items: [], radiusKm: 0, expanded: false, exact: false, all: [] };
  }

  /* Does one record satisfy one search? Coordinates decide when both
     sides have them; text decides when they do not. Legacy listings
     that were saved before pinning existed still have to be findable,
     so the text path is a real path and not an apology. */
  function match(item, target, o) {
    o = o || {};
    if (!target) return true;

    var lat = Number(item[o.latKey || 'lat']);
    var lng = Number(item[o.lngKey || 'lng']);

    if (isFinite(lat) && isFinite(lng) && isFinite(target.lat)) {
      var km = distance(target, { lat: lat, lng: lng });
      if (km <= (o.radiusKm || radiusFor(target, 25))) return true;
      /* Outside the circle but the text still says the same city —
         a listing pinned to the wrong side of a big metro should not
         vanish from a search for that metro. */
      if (o.strict) return false;
    }

    var hay = norm([
      item.location, item.city, item.area, item.name, item.title, item.country
    ].filter(Boolean).join(' '));
    if (!hay) return false;

    var needles = [target.name, target.city, target.area].filter(Boolean).map(norm);
    for (var i = 0; i < needles.length; i++) {
      if (needles[i] && hay.indexOf(needles[i]) > -1) return true;
    }
    return false;
  }

  /* A record with no pin, only text. Resolve what we can offline so old
     inventory still plots on a map and still answers a radius search. */
  function parse(text) {
    var hits = searchSeed(text, 1);
    return hits.length ? hits[0] : null;
  }

  /* ════════════════════════════════════════════════════════════════
     5b · COUNTRIES

     The listing form used to offer a choice of five: Kenya, Tanzania,
     Uganda, Rwanda, Ethiopia. Cabana sells stays in Lisbon, Amsterdam
     and Tokyo, so a host in any of them literally could not describe
     where their property was.

     Only the ISO codes are carried. Names come from Intl.DisplayNames,
     which the browser already has in every language it supports — a
     hand-typed list of 249 country names would be both larger and, in
     any language but English, wrong.
     ════════════════════════════════════════════════════════════════ */

  var ISO2 = ('ad ae af ag ai al am ao aq ar as at au aw ax az ba bb bd be bf bg bh bi bj bl bm bn bo bq br bs bt bv bw ' +
    'by bz ca cc cd cf cg ch ci ck cl cm cn co cr cu cv cw cx cy cz de dj dk dm do dz ec ee eg eh er es et fi fj fk fm ' +
    'fo fr ga gb gd ge gf gg gh gi gl gm gn gp gq gr gs gt gu gw gy hk hm hn hr ht hu id ie il im in io iq ir is it je ' +
    'jm jo jp ke kg kh ki km kn kp kr kw ky kz la lb lc li lk lr ls lt lu lv ly ma mc md me mf mg mh mk ml mm mn mo mp ' +
    'mq mr ms mt mu mv mw mx my mz na nc ne nf ng ni nl no np nr nu nz om pa pe pf pg ph pk pl pm pn pr ps pt pw py qa ' +
    're ro rs ru rw sa sb sc sd se sg sh si sj sk sl sm sn so sr ss st sv sx sy sz tc td tf tg th tj tk tl tm tn to tr ' +
    'tt tv tw tz ua ug um us uy uz va vc ve vg vi vn vu wf ws ye yt za zm zw').split(' ');

  /* The countries Cabana actually operates in, for the browser that
     cannot name the rest. Everyone gets a usable list; most get all
     of them. */
  var FALLBACK_NAMES = {
    ke: 'Kenya', tz: 'Tanzania', ug: 'Uganda', rw: 'Rwanda', et: 'Ethiopia',
    ng: 'Nigeria', gh: 'Ghana', za: 'South Africa', ma: 'Morocco', eg: 'Egypt',
    ci: "Côte d'Ivoire", sn: 'Senegal', gb: 'United Kingdom', fr: 'France',
    nl: 'Netherlands', de: 'Germany', es: 'Spain', pt: 'Portugal', it: 'Italy',
    gr: 'Greece', tr: 'Türkiye', ae: 'United Arab Emirates', us: 'United States',
    mx: 'Mexico', br: 'Brazil', th: 'Thailand', jp: 'Japan', sg: 'Singapore',
    au: 'Australia', in: 'India', cn: 'China', ca: 'Canada'
  };

  var _countries = null;

  function countries() {
    if (_countries) return _countries;
    var namer = null;
    try {
      if (typeof Intl !== 'undefined' && Intl.DisplayNames) {
        namer = new Intl.DisplayNames([docLang()], { type: 'region' });
      }
    } catch (e) { namer = null; }

    var out = [];
    for (var i = 0; i < ISO2.length; i++) {
      var cc = ISO2[i];
      var name = null;
      if (namer) {
        try {
          var n = namer.of(cc.toUpperCase());
          /* DisplayNames echoes the code back for regions it does not
             know; a two-letter "name" is a miss, not a country. */
          if (n && n.toLowerCase() !== cc) name = n;
        } catch (e) {}
      }
      if (!name) name = FALLBACK_NAMES[cc] || null;
      if (name) out.push({ code: cc, name: name });
    }
    out.sort(function (a, b) { return a.name.localeCompare(b.name); });
    _countries = out;
    return out;
  }

  /* Turn any <select> into a full country picker, preserving whatever
     was already chosen — including a value the old five-option list
     saved, which must not silently become something else. */
  function fillCountrySelect(el, selected) {
    el = typeof el === 'string' ? document.getElementById(String(el).replace(/^#/, '')) : el;
    if (!el) return null;

    var want = str(selected != null ? selected : el.value || el.getAttribute('data-value'));
    var list = countries();
    var html = '<option value="">Select a country</option>';
    var matched = '';

    for (var i = 0; i < list.length; i++) {
      var c = list[i];
      var isMatch = want && (norm(c.name) === norm(want) || c.code === want.toLowerCase());
      if (isMatch) matched = c.name;
      html += '<option value="' + c.name + '" data-cc="' + c.code + '"' +
              (isMatch ? ' selected' : '') + '>' + c.name + '</option>';
    }

    /* A stored country the list does not contain is still that host's
       answer. Keep it rather than reset their listing to blank. */
    if (want && !matched) {
      html += '<option value="' + want + '" selected>' + want + '</option>';
    }

    el.innerHTML = html;
    return el;
  }

  /* ════════════════════════════════════════════════════════════════
     6 · THE WIDGET

     One typeahead, attached to any input on any page. It owns its own
     markup and styles so a page adds a worldwide address search in one
     line and inherits every fix made here afterwards.
     ════════════════════════════════════════════════════════════════ */

  var CSS = [
    '.apa-geo-wrap{position:relative;}',
    '.apa-geo-pop{position:absolute;left:0;right:0;top:calc(100% + 6px);z-index:9500;',
    'background:#fff;border:1px solid rgba(10,10,20,.12);border-radius:14px;overflow:hidden;',
    'box-shadow:0 18px 48px rgba(10,10,20,.16);max-height:340px;overflow-y:auto;',
    '-webkit-overflow-scrolling:touch;font-family:inherit;}',
    '.apa-geo-pop[hidden]{display:none;}',
    '.apa-geo-opt{display:flex;align-items:flex-start;gap:10px;padding:10px 13px;cursor:pointer;',
    'border-bottom:1px solid rgba(10,10,20,.05);color:#1A1B2E;text-align:left;width:100%;',
    'background:none;border-left:0;border-right:0;border-top:0;font:inherit;}',
    '.apa-geo-opt:last-child{border-bottom:none;}',
    '.apa-geo-opt:hover,.apa-geo-opt[aria-selected="true"]{background:#F3F4FB;}',
    '.apa-geo-ico{flex:0 0 auto;font-size:15px;line-height:1.3;width:20px;text-align:center;}',
    '.apa-geo-txt{min-width:0;flex:1;}',
    '.apa-geo-name{font-size:13.5px;font-weight:600;line-height:1.35;',
    'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
    '.apa-geo-name b{font-weight:800;color:#4361FF;}',
    '.apa-geo-sub{font-size:11.5px;color:#8E90AD;margin-top:1px;line-height:1.35;',
    'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}',
    '.apa-geo-far{flex:0 0 auto;font-size:11px;color:#8E90AD;padding-top:2px;}',
    '.apa-geo-note{padding:9px 13px;font-size:11px;font-weight:700;letter-spacing:.04em;',
    'text-transform:uppercase;color:#8E90AD;background:#FAFAFD;}',
    '.apa-geo-msg{padding:13px;font-size:12.5px;color:#8E90AD;text-align:center;}',
    '.apa-geo-me{color:#4361FF;font-weight:650;}',
    '@media (max-width:640px){.apa-geo-pop{max-height:60vh;}}',
    '@media (prefers-color-scheme:dark){',
    '.apa-geo-pop{background:#181926;border-color:rgba(255,255,255,.12);}',
    '.apa-geo-opt{color:#EDEEF5;border-bottom-color:rgba(255,255,255,.06);}',
    '.apa-geo-opt:hover,.apa-geo-opt[aria-selected="true"]{background:#22243450;}',
    '.apa-geo-note{background:#14151F;}}'
  ].join('');

  function injectCSS() {
    if (document.getElementById('apa-geo-css')) return;
    var s = document.createElement('style');
    s.id = 'apa-geo-css';
    s.textContent = CSS;
    (document.head || document.documentElement).appendChild(s);
  }

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }

  /* Bold the part the person actually typed. Small thing; it is the
     difference between a list you scan and a list you read. */
  function highlight(text, q) {
    var t = String(text || '');
    var needle = str(q);
    if (!needle) return esc(t);
    var i = t.toLowerCase().indexOf(needle.toLowerCase());
    if (i < 0) return esc(t);
    return esc(t.slice(0, i)) + '<b>' + esc(t.slice(i, i + needle.length)) + '</b>' +
           esc(t.slice(i + needle.length));
  }

  var ICONS = {
    airport: '✈️', transport: '🚉', poi: '📌', address: '🏠', street: '🛣️',
    neighbourhood: '🏘️', city: '🏙️', region: '🗺️', country: '🌍', place: '📍'
  };

  var uid = 0;

  /* Attach the typeahead.

       o.onPick(place)     what to do with the answer — the whole point
       o.onClear()         fired when the user empties or invalidates it
       o.country           restrict, when a form is genuinely one country
       o.near              bias point (defaults to the remembered bias)
       o.limit             suggestions to show (default 6)
       o.myLocation        show the "use my location" row (default true)
       o.recents           show recent picks on empty focus (default true)
       o.latField/lngField ids or elements of hidden inputs to fill
       o.value             a place to show as already chosen
       o.minChars          override the 2-character floor
       o.placeholder       replace the input's placeholder

     Returns a handle: { input, get, set, clear, destroy, refresh }. */
  function attach(input, o) {
    o = o || {};
    input = typeof input === 'string' ? document.getElementById(String(input).replace(/^#/, '')) : input;
    if (!input || input._apaGeo) return input ? input._apaGeo : null;

    injectCSS();

    var minChars = o.minChars != null ? o.minChars : MIN_CHARS;
    var limit = o.limit || 6;
    var onPick = o.onPick || function () {};
    var onClear = o.onClear || function () {};

    var latField = fieldOf(o.latField);
    var lngField = fieldOf(o.lngField);

    var id = 'apa-geo-' + (++uid);
    var wrap = input.parentNode;
    if (!wrap) return null;
    if (getComputedStyle(wrap).position === 'static') wrap.style.position = 'relative';
    wrap.classList.add('apa-geo-wrap');

    var pop = document.createElement('div');
    pop.className = 'apa-geo-pop';
    pop.id = id + '-list';
    pop.setAttribute('role', 'listbox');
    pop.hidden = true;
    wrap.appendChild(pop);

    /* A combobox that screen readers can actually drive. The browser's
       own autofill is turned off — it offers a street the user typed on
       a different site and it covers our list. */
    input.setAttribute('role', 'combobox');
    input.setAttribute('aria-autocomplete', 'list');
    input.setAttribute('aria-expanded', 'false');
    input.setAttribute('aria-controls', pop.id);
    input.setAttribute('autocomplete', 'off');
    input.setAttribute('autocapitalize', 'off');
    input.setAttribute('spellcheck', 'false');
    if (o.placeholder) input.placeholder = o.placeholder;

    var rows = [];       // what is currently listed
    var hi = -1;         // highlighted index
    var chosen = null;   // the resolved place, or null
    var timer = null;
    var ctrl = null;     // AbortController for the in-flight request
    var seq = 0;         // guards against a slow response overwriting a fast one
    var open = false;
    var programmatic = false;  // true while we are writing input.value ourselves

    function fieldOf(f) {
      if (!f) return null;
      return typeof f === 'string' ? document.getElementById(String(f).replace(/^#/, '')) : f;
    }

    function setOpen(v) {
      open = v;
      pop.hidden = !v;
      input.setAttribute('aria-expanded', v ? 'true' : 'false');
      if (!v) {
        hi = -1;
        input.removeAttribute('aria-activedescendant');
      }
    }

    function paint(list, opts) {
      opts = opts || {};
      rows = list;
      hi = -1;

      var html = '';
      if (opts.note) html += '<div class="apa-geo-note">' + esc(opts.note) + '</div>';

      if (!list.length) {
        html += '<div class="apa-geo-msg">' +
                esc(opts.empty || 'No place found. Try a nearby town or a landmark.') +
                '</div>';
      } else {
        html += list.map(function (r, i) {
          if (r._action) {
            return '<button type="button" class="apa-geo-opt" role="option" id="' + id + '-o' + i +
                   '" data-i="' + i + '" aria-selected="false">' +
                   '<span class="apa-geo-ico">' + r.icon + '</span>' +
                   '<span class="apa-geo-txt"><span class="apa-geo-name apa-geo-me">' +
                   esc(r.title) + '</span></span></button>';
          }
          var sub = [r.area, r.city, r.state, r.country].filter(uniqTruthy()).slice(0, 3).join(', ');
          return '<button type="button" class="apa-geo-opt" role="option" id="' + id + '-o' + i +
                 '" data-i="' + i + '" aria-selected="false">' +
                 '<span class="apa-geo-ico">' + (ICONS[r.kind] || ICONS.place) + '</span>' +
                 '<span class="apa-geo-txt">' +
                 '<span class="apa-geo-name">' + highlight(r.name || r.short, opts.q) + '</span>' +
                 (sub ? '<span class="apa-geo-sub">' + esc(sub) + '</span>' : '') +
                 '</span>' +
                 (r.distanceKm != null && r.distanceKm < 400
                    ? '<span class="apa-geo-far">' + fmtKm(r.distanceKm) + '</span>' : '') +
                 '</button>';
        }).join('');
      }

      pop.innerHTML = html;
      setOpen(true);
    }

    function move(step) {
      var opts = pop.querySelectorAll('.apa-geo-opt');
      if (!opts.length) return;
      hi = (hi + step + opts.length) % opts.length;
      for (var i = 0; i < opts.length; i++) {
        opts[i].setAttribute('aria-selected', i === hi ? 'true' : 'false');
      }
      input.setAttribute('aria-activedescendant', opts[hi].id);
      /* Keeping the highlighted row visible is a nicety; it must never
         be the thing that throws and kills arrow-key navigation. */
      if (opts[hi].scrollIntoView) opts[hi].scrollIntoView({ block: 'nearest' });
    }

    function choose(i) {
      var r = rows[i];
      if (!r) return;

      if (r._action === 'locate') {
        paint([], { empty: 'Finding you…' });
        locate().then(function (p) {
          commit(p);
        }).catch(function (e) {
          paint([], { empty: e.message });
        });
        return;
      }

      commit(r);
    }

    function commit(p) {
      chosen = p;
      input.value = o.display ? o.display(p) : (p.short || p.label || p.name);
      input.dataset.lat = p.lat;
      input.dataset.lng = p.lng;
      input.dataset.placeId = p.id || '';
      if (latField) latField.value = p.lat;
      if (lngField) lngField.value = p.lng;
      setOpen(false);
      remember(p);
      onPick(p);

      /* Pages wired to native events — `onchange="applySearch()"` and
         friends — have to hear about a pick, but writing input.value
         above is our own edit, not the user's. Without this flag the
         change event re-enters onInput, which treats it as typing,
         throws away the pin that was just set and reopens the list.
         Only `change` is dispatched: `input` means a human typed. */
      programmatic = true;
      try {
        input.dispatchEvent(new Event('change', { bubbles: true }));
      } finally {
        programmatic = false;
      }
    }

    function invalidate() {
      if (!chosen) return;
      chosen = null;
      delete input.dataset.lat;
      delete input.dataset.lng;
      delete input.dataset.placeId;
      if (latField) latField.value = '';
      if (lngField) lngField.value = '';
      onClear();
    }

    function actionRows() {
      var list = [];
      if (o.myLocation !== false && navigator.geolocation) {
        list.push({ _action: 'locate', icon: '🎯', title: 'Use my current location' });
      }
      return list;
    }

    function firstResult() {
      for (var i = 0; i < rows.length; i++) if (!rows[i]._action) return i;
      return -1;
    }

    /* An empty, focused box. Rather than nothing, offer the two things
       that are true before a single character is typed: where the person
       is, and where they were looking last time. */
    function showIdle() {
      var list = actionRows().concat(o.recents === false ? [] : recents().map(place));
      if (!list.length) { setOpen(false); return; }
      paint(list, { empty: '' });
    }

    function run(q) {
      var mine = ++seq;

      /* Something on screen immediately, from the gazetteer, while the
         network is still deciding. */
      var instant = searchSeed(q, limit);
      if (instant.length) paint(actionRows().concat(instant), { q: q });
      else paint([], { empty: 'Searching…' });

      if (ctrl) ctrl.abort();
      ctrl = typeof AbortController !== 'undefined' ? new AbortController() : null;

      search(q, {
        limit: limit,
        country: o.country,
        near: o.near || undefined,
        signal: ctrl ? ctrl.signal : undefined
      }).then(function (list) {
        if (mine !== seq) return;   // a later keystroke already won
        paint(actionRows().concat(list), { q: q });
      }).catch(function () {
        if (mine !== seq) return;
        if (!instant.length) paint([], { q: q });
      });
    }

    function onInput() {
      if (programmatic) return;
      invalidate();
      clearTimeout(timer);
      var q = input.value.trim();
      if (q.length < minChars) {
        if (!q) { onClear(); showIdle(); }
        else setOpen(false);
        return;
      }
      timer = setTimeout(function () { run(q); }, DEBOUNCE);
    }

    input.addEventListener('input', onInput);

    input.addEventListener('focus', function () {
      var q = input.value.trim();
      if (q.length >= minChars && !chosen) run(q);
      else if (!q) showIdle();
    });

    input.addEventListener('keydown', function (e) {
      if (e.key === 'ArrowDown') { e.preventDefault(); if (!open) onInput(); else move(1); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); move(-1); }
      else if (e.key === 'Enter') {
        if (open && hi >= 0) { e.preventDefault(); choose(hi); }
        else if (open) {
          /* Nothing highlighted: take the best real suggestion, skipping
             the action rows. "Use my current location" must never be
             what a blind press of Enter selects. */
          var first = firstResult();
          if (first >= 0) { e.preventDefault(); choose(first); }
        }
        /* Still nothing to pick: let the form submit. A search box that
           swallows Enter is worse than one with no autocomplete. */
      } else if (e.key === 'Escape') { if (open) { e.stopPropagation(); setOpen(false); } }
      else if (e.key === 'Tab') { if (open && hi >= 0) choose(hi); else setOpen(false); }
    });

    /* mousedown, not click: blur fires first on a click and would close
       the list out from under the pointer. */
    pop.addEventListener('mousedown', function (e) {
      var btn = e.target.closest ? e.target.closest('.apa-geo-opt') : null;
      if (!btn) return;
      e.preventDefault();
      choose(parseInt(btn.dataset.i, 10));
    });

    input.addEventListener('blur', function () { setTimeout(function () { setOpen(false); }, 140); });

    var handle = {
      input: input,
      get: function () { return chosen; },
      set: function (p, opts) {
        if (!p) return handle.clear();
        var full = place(p);
        chosen = full;
        input.value = (opts && opts.text) || full.short || full.label;
        input.dataset.lat = full.lat;
        input.dataset.lng = full.lng;
        if (latField) latField.value = full.lat;
        if (lngField) lngField.value = full.lng;
      },
      clear: function () {
        chosen = null;
        input.value = '';
        delete input.dataset.lat;
        delete input.dataset.lng;
        delete input.dataset.placeId;
        if (latField) latField.value = '';
        if (lngField) lngField.value = '';
        setOpen(false);
      },
      /* Re-run the current text, for a page with its own search button
         next to the box. */
      search: function () {
        var q = input.value.trim();
        if (q.length >= minChars) run(q);
        return handle;
      },
      /* Resolve whatever is typed without the user picking a row —
         for a form that is being submitted with the box left open. */
      resolve: function () {
        if (chosen) return Promise.resolve(chosen);
        var q = input.value.trim();
        if (q.length < minChars) return Promise.resolve(null);
        return search(q, { limit: 1, country: o.country }).then(function (r) {
          if (r.length) { chosen = r[0]; return r[0]; }
          return null;
        });
      },
      destroy: function () {
        clearTimeout(timer);
        if (ctrl) ctrl.abort();
        if (pop.parentNode) pop.parentNode.removeChild(pop);
        delete input._apaGeo;
      }
    };

    if (o.value) handle.set(o.value);
    input._apaGeo = handle;
    return handle;
  }

  function fmtKm(km) {
    if (km == null) return '';
    if (km < 1) return Math.round(km * 1000) + ' m';
    if (km < 10) return km.toFixed(1) + ' km';
    return Math.round(km) + ' km';
  }

  /* Wire every input the markup has flagged, so a new page needs no
     script at all — just `data-apa-geo` and, optionally, the fields to
     fill. Idempotent: safe to call again after rendering more markup. */
  function autoWire(root) {
    var scope = root || document;
    var nodes = scope.querySelectorAll('[data-apa-geo]');
    var made = [];
    for (var i = 0; i < nodes.length; i++) {
      var el = nodes[i];
      if (el._apaGeo) continue;
      made.push(attach(el, {
        country: el.getAttribute('data-geo-country') || undefined,
        limit: parseInt(el.getAttribute('data-geo-limit'), 10) || undefined,
        latField: el.getAttribute('data-geo-lat') || undefined,
        lngField: el.getAttribute('data-geo-lng') || undefined,
        myLocation: el.getAttribute('data-geo-locate') !== 'off',
        recents: el.getAttribute('data-geo-recents') !== 'off'
      }));
    }
    return made;
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { autoWire(); });
  } else {
    autoWire();
  }

  window.ApaGeo = {
    search: search,
    reverse: reverse,
    locate: locate,
    attach: attach,
    autoWire: autoWire,
    distance: distance,
    nearby: nearby,
    match: match,
    radiusFor: radiusFor,
    parse: parse,
    place: place,
    countries: countries,
    fillCountrySelect: fillCountrySelect,
    seed: searchSeed,
    recents: recents,
    remember: remember,
    bias: getBias,
    setBias: setBias,
    formatKm: fmtKm,
    normalize: norm,
    GAZETTEER: SEED
  };
})();
