-- Cabana Flight Desk · airline reference data

insert into public.airlines (iata,icao,name,country,country_code,route_count) values
('FR','RYR','Ryanair','Ireland','IE',2484),
('AA','AAL','American Airlines','United States','US',2354),
('UA','UAL','United Airlines','United States','US',2180),
('DL','DAL','Delta Air Lines','United States','US',1981),
('US','USA','US Airways','United States','US',1960),
('CZ','CSN','China Southern','China','CN',1454),
('MU','CES','China Eastern','China','CN',1263),
('CA','CCA','Air China','China','CN',1260),
('WN','SWA','Southwest Airlines','United States','US',1146),
('U2','EZY','easyJet','United Kingdom','GB',1130),
('AF','AFR','Air France','France','FR',1071),
('LH','DLH','Lufthansa','Germany','DE',923),
('AZ','AZA','Alitalia','Italy','IT',877),
('IB','IBE','Iberia Airlines','Spain','ES',831),
('KL','KLM','KLM','Netherlands','NL',830),
('ZH','CSZ','Shenzhen Airlines','China','CN',815),
('AB','BER','Air Berlin','Germany','DE',798),
('FL','TRS','AirTran Airways','United States','US',726),
('AC','ACA','Air Canada','Canada','CA',705),
('TK','THY','Turkish Airlines','Turkey','TR',658),
('DY','NAX','Norwegian Air Shuttle','Norway','NO',576),
('HU','CHH','Hainan Airlines','China','CN',555),
('BA','BAW','British Airways','United Kingdom','GB',549),
('NH','ANA','All Nippon Airways','Japan','JP',547),
('AS','ASA','Alaska Airlines','ALASKA',null,530),
('SK','SAS','Scandinavian Airlines System','Sweden','SE',504),
('TO','PSD','President Airlines','Cambodia','KH',488),
('SU','AFL','Aeroflot Russian Airlines','Russia',null,473),
('4U','GWI','Germanwings','Germany','DE',470),
('W6','WZZ','Wizz Air','Hungary','HU',463),
('QF','QFA','Qantas','Australia','AU',432),
('AM','AMX','AeroMéxico','Mexico','MX',431),
('B6','JBU','JetBlue Airways','United States','US',399),
('AD','PRZ','Air Paradise International','Indonesia','ID',397),
('AI','AIC','Air India','India','IN',393),
('3U','CSC','Sichuan Airlines','China','CN',392),
('JL','JAL','Japan Airlines','Japan','JP',388),
('MF','CXA','Xiamen Airlines','China','CN',386),
('VY','FOS','Formosa Airlines','Taiwan',null,384),
('SV','SVA','Saudia','Saudi Arabia','SA',383),
('G4','AAY','Allegiant Air','United States','US',378),
('GS','UPA','Air Foyle','United Kingdom','GB',358),
('WS','WJA','WestJet','Canada','CA',341),
('ET','ETH','Ethiopian Airlines','Ethiopia','ET',337),
('MH','MAS','Malaysia Airlines','Malaysia','MY',336),
('DE','CFG','Condor Flugdienst','Germany','DE',334),
('JJ','TAM','TAM Brazilian Airlines','Brazil','BR',333),
('G3','CIX','City Connexion Airlines','Burundi','BI',332),
('AY','FIN','Finnair','Finland','FI',328),
('SC','CDG','Shandong Airlines','China','CN',314),
('LS','EXS','Jet2.com','United Kingdom','GB',302),
('UN','TSO','Transaero Airlines','Russia',null,300),
('9W','JAI','Jet Airways','India','IN',292),
('KE','KAL','Korean Air','Republic of Korea',null,292),
('LX','SWR','SWISS','Switzerland','CH',290),
('VA','VAU','V Australia Airlines','Australia','AU',290),
('EK','UAE','Emirates','United Arab Emirates','AE',289),
('AV','AVA','Avianca - Aerovias Nacionales de Colombia','AVIANCA',null,286),
('LA','LAN','LAN Airlines','Chile','CL',285),
('S7','SBI','S7 Airlines','Russia',null,281),
('QR','QTR','Qatar Airways','Qatar','QA',278),
('BE','BEE','Flybe','United Kingdom','GB',268),
('OZ','AAR','Asiana Airlines','Republic of Korea',null,262),
('JT','LNI','Lion Mentari Airlines','Indonesia','ID',251),
('GA','GIA','Garuda Indonesia','Indonesia','ID',248),
('NK','NKS','Spirit Airlines','United States','US',242),
('PC','PGT','Pegasus Airlines','Turkey','TR',242),
('PK','PIA','Pakistan International Airlines','Pakistan','PK',242),
('AT','RAM','Royal Air Maroc','Morocco','MA',240),
('OS','AUA','Austrian Airlines','Austria','AT',240),
('AH','DAH','Air Algérie','Algeria','DZ',234),
('HV','TRA','Transavia Holland','Netherlands','NL',233),
('NZ','ANZ','Air New Zealand','New Zealand','NZ',233),
('U6','SVR','Ural Airlines','Russia',null,232),
('TP','TAP','TAP Portugal','Portugal','PT',229),
('EY','ETD','Etihad Airways','United Arab Emirates','AE',228),
('6E','IGO','IndiGo','India','IN',227),
('EI','EIN','Aer Lingus','Ireland','IE',226),
('X3','HLX','TUIfly','Germany','DE',226),
('7H','ERR','Era Alaska','United States','US',224),
('A3','AEE','Aegean Airlines','Greece','GR',222),
('F9','FFT','Frontier Airlines','United States','US',222),
('JD','JAS','Japan Air System','Japan','JP',214),
('CX','CPA','Cathay Pacific','Hong Kong','HK',213),
('SQ','SIA','Singapore Airlines','Singapore','SG',212),
('VN','HVN','Vietnam Airlines','Vietnam',null,211),
('WF','WIF','Widerøe','Norway','NO',210),
('ZB','BUB','Air Bourbon','Reunion',null,210),
('MS','MSR','EgyptAir','Egypt','EG',205),
('SA','SAA','South African Airways','South Africa','ZA',202),
('Y4','VOI','Volaris','Mexico','MX',197),
('SG','JGO','JetsGo','Canada','CA',196),
('VS','VIR','Virgin Atlantic','United Kingdom','GB',195),
('FM','CSH','Shanghai Airlines','China','CN',193),
('TG','THA','Thai Airways International','Thailand','TH',193),
('SN','BEL','Brussels Airlines','Belgium','BE',190),
('IR','IRA','Iran Air','Iran',null,186),
('5J','CEB','Cebu Pacific','Philippines','PH',184),
('CM','CMP','Copa Airlines','Panama','PA',184),
('EP','IRC','Iran Aseman Airlines','Iran',null,183),
('AK','AXM','AirAsia','Malaysia','MY',180),
('S2','RSH','Air Sahara','India','IN',180),
('IG','ISS','Meridiana','Italy','IT',173),
('CI','CAL','China Airlines','Taiwan',null,172),
('JQ','JST','Jetstar Airways','Australia','AU',163),
('UX','AEA','Air Europa','Spain','ES',158),
('9C','\N','China SSS','China','CN',155),
('AR','ARG','Aerolineas Argentinas','Argentina','AR',154),
('HY','UZB','Uzbekistan Airways','Uzbekistan','UZ',151),
('TU','TAR','Tunisair','Tunisia','TN',151),
('A5','RLA','Airlinair','France','FR',150),
('FZ','FDB','flydubai','United Arab Emirates','AE',148),
('HO','DJA','Antinea Airlines','Algeria','DZ',145),
('PR','PAL','Philippine Airlines','Philippines','PH',144),
('KQ','KQA','Kenya Airways','Kenya','KE',142),
('TS','TSC','Air Transat','Canada','CA',138),
('V7','SNG','Air Senegal International','Senegal','SN',136),
('8L','CGP','Cargo Plus Aviation','United Arab Emirates','AE',130),
('G9','ABY','Air Arabia','United Arab Emirates','AE',130),
('PS','PSX','Pacific Southwest Airlines','United States','US',127),
('GL','GRL','Air Greenland','Denmark','DK',126),
('RJ','RJA','Royal Jordanian','Jordan','JO',122),
('LO','LOT','LOT Polish Airlines','Poland','PL',120),
('BR','EVA','EVA Air','Taiwan',null,118),
('KC','KZR','Air Astana','Kazakhstan','KZ',118),
('4O','\N','Interjet (ABC Aerolineas)','Mexico','MX',114),
('BT','BTI','Air Baltic','Latvia','LV',112),
('OU','CTN','Croatia Airlines','Croatia','HR',112),
('HG','NLY','Niki','Austria','AT',111),
('OK','CSA','Czech Airlines','Czech Republic',null,111),
('LG','LGL','Luxair','Luxembourg','LU',110),
('OA','OAL','Olympic Airlines','Greece','GR',110),
('XY','KNE','flynas','Saudi Arabia','SA',110),
('BK','PDC','Potomac Air','United States','US',106),
('SJ','SJY','Sriwijaya Air','Indonesia','ID',106),
('O6','ONE','Oceanair','Brazil','BR',104),
('VB','\N','Birmingham European','United Kingdom','GB',102),
('XQ','SXS','SunExpress','Turkey',null,99),
('KN','\N','China United','China','CN',98),
('WY','OMA','Oman Air','Oman','OM',98),
('PX','ANG','Air Niugini','Papua New Guinea','PG',97),
('VT','VTA','Air Tahiti','French Polynesia','PF',97),
('IY','IYE','Yemenia','Yemen','YE',96),
('KA','HDA','Dragonair','DRAGON',null,96),
('ST','GMI','Germania','Germany','DE',96),
('G5','\N','Huaxia','China','CN',94),
('MI','SLK','SilkAir','Singapore','SG',93),
('UL','ALK','SriLankan Airlines','Sri Lanka','LK',93),
('FD','AIQ','Thai AirAsia','Thailand','TH',92),
('GE','TNA','TransAsia Airways','Taiwan',null,92),
('NF','AVN','Air Vanuatu','Vanuatu','VU',92),
('RO','ROT','Tarom','Romania','RO',92),
('PN','CHB','West Air China','China','CN',90),
('AP','AIB','Airbus Industrie','France','FR',88),
('HQ','HMY','Harmony Airways','Canada','CA',88),
('ZL','RXA','Regional Express','Australia','AU',88),
('R3','SYL','Aircompany Yakutia','Russia',null,87),
('9K','KAP','Cape Air','United States','US',86),
('KM','AMC','Air Malta','Malta','MT',84),
('B2','BRU','Belavia Belarusian Airlines','Belarus','BY',82),
('CG','TOK','Airlines PNG','Papua New Guinea','PG',82),
('S4','RZO','SATA International','Portugal','PT',81),
('DV','LTF','Lufttaxi Fluggesellschaft','Germany','DE',80),
('EU','EEA','Empresa Ecuatoriana De Aviacion','Ecuador','EC',80),
('V0','VCV','Conviasa','Venezuela',null,80),
('KU','KAC','Kuwait Airways','Kuwait','KW',79),
('Y7','\N','NordStar Airlines','Russia',null,78),
('G8','AGB','Air Service Gabon','Gabon','GA',77),
('GF','GFA','Gulf Air','Bahrain','BH',77),
('JU','JAT','Jat Airways','Serbia','RS',77),
('9R','VAP','Phuket Air','Thailand','TH',76),
('IX','AXB','Air India Express','India','IN',76),
('TR','TGW','Tiger Airways','Singapore','SG',76),
('UR','\N','UTair-Express','Russia',null,76),
('W3','ARA','Arik Air','Nigeria','NG',76),
('MD','MDG','Madagascar Airlines','Madagascar','MG',75),
('PG','BKP','Bangkok Airways','Thailand','TH',75),
('7F','FAB','First Air','Canada','CA',74),
('8E','BRG','Bering Air','United States','US',74),
('HA','HAL','Hawaiian Airlines','United States','US',74),
('LN','LAA','Libyan Arab Airlines','Libya','LY',74),
('LY','ELY','El Al Israel Airlines','Israel','IL',73),
('7R','BRB','BRA-Transportes Aereos','Brazil','BR',72),
('ZI','AAF','Aigle Azur','France','FR',72),
('DT','DTA','TAAG Angola Airlines','Angola','AO',71),
('3M','\N','Silver Airways (3M)','United States','US',67),
('QS','QSC','African Safari Airways','Kenya','KE',67),
('FJ','FJI','Air Pacific','Fiji','FJ',66),
('VX','VRD','Virgin America','United States','US',66),
('5T','MPE','Canadian North','Canada','CA',65),
('ME','MEA','Middle East Airlines','Lebanon','LB',65),
('BW','BWA','Caribbean Airlines','Trinidad and Tobago','TT',64),
('NL','SAI','Shaheen Air International','Pakistan','PK',64),
('LI','LIA','Leeward Islands Air Transport','Antigua and Barbuda','AG',62),
('NS','\N','Caucasus Airlines','Georgia','GE',62),
('QZ','AWQ','Indonesia AirAsia','Indonesia','ID',62),
('W2','FXT','FlexFlight','South Africa','ZA',62),
('YC','YCC','Ciel Canadien','Canada','CA',62),
('ZK','GLA','Great Lakes Airlines','United States','US',61),
('IE','SOL','Solomon Airlines','Solomon Islands','SB',60),
('CU','CUB','Cubana de Aviación','Cuba','CU',59),
('BC','SKY','Skymark Airlines','Japan','JP',58),
('Q6','CDP','Aero Condor Peru','Peru','PE',58),
('QG','\N','Citilink Indonesia','Indonesia','ID',58),
('UP','BHS','Bahamasair','Bahamas','BS',58),
('AE','MDA','Mandarin Airlines','Taiwan',null,56),
('FB','LZB','Bulgaria Air','Bulgaria','BG',56),
('NX','AMU','Air Macau','Macao','MO',56),
('J2','AHY','Azerbaijan Airlines','Azerbaijan','AZ',54),
('TM','LAM','LAM Mozambique','Mozambique','MZ',54),
('FI','ICE','Icelandair','Iceland','IS',53),
('KY','EQL','Air S','Air S',null,52),
('MJ','LPR','L','Argentina','AR',52),
('MO','AUH','Abu Dhabi Amiri Flight','United Arab Emirates','AE',52),
('9N','N78','Regional Air Iceland','Iceland','IS',50),
('B7','UIA','Uni Air','Taiwan',null,50),
('BV','BPA','Blue Panorama Airlines','Italy','IT',49),
('H2','SKU','Sky Airline','Chile','CL',49),
('HX','CRK','Hong Kong Airlines','Hong Kong SAR of China',null,49),
('EQ','TAE','TAME','Ecuador','EC',48),
('QV','LAO','Lao Airlines','Lao Peoples Democratic Republic',null,48),
('SZ','\N','Salzburg arrows','Austria','AT',48),
('2Z','CGN','Changan Airlines','China','CN',46),
('9E','FLG','Pinnacle Airlines','United States','US',46),
('B9','BGD','Air Bangladesh','Bangladesh','BD',46),
('BG','BBC','Biman Bangladesh Airlines','Bangladesh','BD',46),
('DD','NOK','Nok Air','Thailand','TH',46),
('NT','IBB','Binter Canarias','Spain','ES',46),
('OD','ULA','Zuliana de Aviacion','Venezuela',null,46),
('7I','\N','Insel Air (7I/INC) (Priv)','Netherlands Antilles',null,45),
('3O','\N','Air Arabia Maroc','Morocco','MA',44),
('8U','AAW','Afriqiyah Airways','Libya','LY',44),
('MK','MAU','Air Mauritius','Mauritius','MU',43),
('2B','ARD','Aerocondor','Portugal','PT',42),
('TT','KLA','Air Lithuania','Lithuania','LT',42),
('TV','VEX','Virgin Express','Belgium','BE',42),
('VW','TAO','Aeromar','Mexico','MX',42),
('WU','WAU','Wizz Air Ukraine','Ukraine','UA',42),
('XK','CCM','Corse-Mediterranee','France','FR',42),
('2N','NTJ','NextJet','Sweden','SE',41),
('BU','BRA','Braathens','Norway','NO',41),
('FY','FFM','Firefly','Malaysia','MY',40),
('JP','ADR','Adria Airways','Slovenia','SI',40),
('WB','RWD','RwandAir','Rwanda','RW',40),
('8V','ACP','Astral Aviation','Kenya','KE',39),
('JV','BLS','Bearskin Lake Air Service','Canada','CA',39),
('K5','ABE','Aban Air','Iran',null,39),
('Z8','AZN','Amaszonas','Bolivia',null,39),
('9U','MLD','Air Moldova','Moldova',null,38),
('F7','BBO','Flybaboo','Switzerland','CH',38),
('SY','SCX','Sun Country Airlines','United States','US',38),
('VR','TCV','TACV','Portugal','PT',38),
('WJ','WEB','WebJet Linhas A','Brazil','BR',38),
('3K','JSA','Jetstar Asia Airways','Singapore','SG',36),
('4Y','RBU','Airbus France','France','FR',36),
('8Q','BAJ','Baker Aviation','United States','US',36),
('BJ','LBT','Nouvel Air Tunisie','Tunisia','TN',36),
('D7','RDN','Dinar','Argentina','AR',36),
('GQ','BSY','Big Sky Airlines','United States','US',36),
('K2','ELO','Eurolot','Poland','PL',36),
('TF','SCW','Malmö Aviation','Sweden','SE',36),
('8R','TIB','TRIP Linhas A','Brazil','BR',35),
('SW','NMB','Air Namibia','Namibia','NA',35),
('2P','GAP','Air Philippines','Philippines','PH',34),
('7J','\N','Tajik Air','Tajikistan','TJ',34),
('BB','SBS','Seaborne Airlines','United States','US',34),
('BM',null,'Air Sicilia','Italy','IT',34),
('FO','ATM','Airlines Of Tasmania','Australia','AU',34),
('GV','ARF','Aero Flight','Germany','DE',34),
('PD','POE','Porter Airlines','Canada','CA',34),
('QH','FLZ','Air Florida','United States','US',34),
('SD','SUD','Sudan Airways','Sudan','SD',34),
('VJ','JTY','Jatayu Airlines','Indonesia','ID',34),
('YK',null,'Cyprus Turkish Airlines','Turkey',null,34),
('7C','JJA','Jeju Air','Republic of Korea',null,33),
('TL','ANO','Airnorth','Australia','AU',33),
('4H','UBD','United Airways','Bangladesh','BD',32),
('8P','PCO','Pacific Coastal Airline','Canada','CA',32),
('DN','SGG','Senegal Airlines','Senegal','SN',32),
('FW','IBX','Ibex Airlines','Japan','JP',32),
('KK','KKK','Atlasjet','Turkey',null,32),
('MM','\N','Peach Aviation','Japan','JP',32),
('MY','MXJ','Maxjet Airways','United States','US',32),
('SE','SEU','XL Airways France','France','FR',32),
('T3','EZE','Eastern Airways','United Kingdom','GB',32),
('UJ','LMU','AlMasria Universal Airlines','Egypt','EG',32),
('Z2','\N','Zest Air','Philippines','PH',32),
('9V','VC9','Volotea Costa Rica','Costa Rica','CR',31),
('CY','CYP','Cyprus Airways','Cyprus','CY',31),
('PW','PRF','Precision Air','Tanzania','TZ',31),
('3G','AYZ','Atlant-Soyuz Airlines','Russia',null,30),
('6R','DRU','Alrosa Mirny Air Enterprise','Russia',null,30),
('BI','RBA','Royal Brunei Airlines','Brunei',null,30),
('J9','GIF','Guinee Airlines','Guinea','GN',30),
('L6','MAI','Mauritania Airlines International','Mauritania','MR',30),
('Q2','\N','Maldivian','Maldives','MV',30),
('SS','CRL','Corsairfly','France','FR',30),
('WX','BCY','CityJet','Ireland','IE',30),
('Y8','YZR','Yangtze River Express','China','CN',30),
('5C','ICL','CAL Cargo Air Lines','Israel','IL',29),
('W9','AAB','Abelag Aviation','Belgium','BE',29),
('BX','CST','Coast Air','Norway','NO',28),
('GK',null,'Go One Airways','United Kingdom','GB',28),
('JY','TCI','Air Turks and Caicos','Turks and Caicos Islands','TC',28),
('KS','PEN','Peninsula Airways','United States','US',28),
('OB','ASZ','Astrakhan Airlines','Russia',null,28),
('SP','SAT','SATA Air Acores','Portugal','PT',28),
('TX','FWI','Air Caraïbes','France','FR',28),
('7P','BTV','Metro Batavia','Indonesia','ID',27),
('YI','\N','TUR Avrupa Hava YollarÄ±','Turkey',null,27),
('3L','ISK','Intersky','Austria','AT',26),
('B5','FLT','Flightline','United Kingdom','GB',26),
('HD','ADO','Hokkaido International Airlines','Japan','JP',26),
('LJ','SLA','Sierra National Airlines','Sierra Leone','SL',26),
('OV','ELL','Estonian Air','Estonia','EE',26),
('R7','OCA','Aserca Airlines','Venezuela',null,26),
('YM','MGX','Montenegro Airlines','Montenegro','ME',26),
('HF','VRE','Air Côte d’Ivoire','Côte d''Ivoire','CI',25),
('IL','ILW','Illinois Airways','United States','US',25),
('QC','CRD','Air Corridor','Mozambique','MZ',25),
('WM','\N','Windward Islands Airways','Netherlands Antilles',null,25),
('3S',null,'Aeroland Airways','Greece','GR',24),
('BP','BOT','Air Botswana','Botswana','BW',24),
('JH','NES','Nordeste Linhas Aereas Regionais','Brazil','BR',24),
('LR','LRC','LACSA','Costa Rica','CR',24),
('OR','TFL','Arkefly','Netherlands','NL',24),
('Q9','SNG','Air Senegal','Senegal','SN',24),
('SX','SRK','Sky Work Airlines','Switzerland','CH',24),
('T7','TJT','Twin Jet','France','FR',24),
('TZ','SCO','Scoot','Singapore','SG',24),
('UG','TUI','Tuninter','Tunisia','TN',24),
('UU','REU','Air Austral','France','FR',24),
('W5','IRM','Mahan Air','Iran',null,24),
('A4','SWD','Southern Winds Airlines','Argentina','AR',23),
('KX','CAY','Cayman Airways','Cayman Islands','KY',23),
('TY','TPC','Air Cal','France','FR',23),
('Y9','IRK','Kish Air','Iran',null,23),
('2J','VBW','Air Burkina','Burkina Faso','BF',22),
('5N','AUL','Aeroflot-Nord','Russia',null,22),
('6T','\N','Air Mandalay','Burma',null,22),
('DG','SRQ','South East Asian Airlines','Philippines','PH',22),
('FG','AFG','Ariana Afghan Airlines','Afghanistan','AF',22),
('K6','BRV','Bravo Air Congo','Democratic Republic of the Congo',null,22),
('KR','CWK','Comores Airlines','Comoros','KM',22),
('NU','JTA','Japan Transocean Air','Japan','JP',22),
('SB','ACI','Air Caledonie International','France','FR',22),
('ZE','AZE','Arcus-Air Logistic','Germany','DE',22),
('2G','CRG','Cargoitalia','Italy','IT',21),
('MR','MRT','Air Mauritanie','Mauritania','MR',21),
('P4','APK','Air Peace','Nigeria','NG',21),
('3R','GAI','Moskovia Airlines','Russia',null,20),
('4G',null,'Advance Leasing Company','United States','US',20),
('DC','GAO','Golden Air','Sweden','SE',20),
('GR','AUR','Aurigny Air Services','United Kingdom','GB',20),
('I6','SEQ','Sky Eyes','Thailand','TH',20),
('IZ','AIZ','Arkia Israel Airlines','Israel','IL',20),
('KB','DRK','Druk Air','Bhutan','BT',20),
('LM','LAM','Linhas A','Mozambique','MZ',20),
('PY','SLM','Surinam Airways','Suriname','SR',20),
('RX','AEH','Aviaexpress','Hungary','HU',20),
('SI','SIH','Skynet Airlines','Ireland','IE',20),
('UO','HKE','Hong Kong Express Airways','Hong Kong SAR of China',null,20),
('Z6','ZTT','ZABAIKAL AIRLINES','Russia',null,20),
('M4','NOV','Nova Airline','Sudan','SD',19),
('MW','MYD','Maya Island Air','Belize','BZ',19),
('2I','\N','Star Peru (2I)','Peru','PE',18),
('5H','FFV','Fly540','Kenya','KE',18),
('5Q','\N','BQB Lineas Aereas','Uruguay','UY',18),
('A9','TGZ','Georgian Airways','Georgia','GE',18),
('BL','PIC','Jetstar Pacific','Vietnam',null,18),
('D2','\N','Severstal Air Company','Russia',null,18),
('EG','JAA','Japan Asia Airways','Japan','JP',18),
('FE','WCP','Primaris Airlines','United States','US',18),
('J3','PLR','Northwestern Air','Canada','CA',18),
('JE','MNO','Mango','South Africa','ZA',18),
('M5','KEN','Kenmore Air','United States','US',18),
('P0',null,'Proflight Commuter Services','Zambia','ZM',18),
('PL','PLI','Aeroper','Peru','PE',18),
('PZ','LAP','TAM Mercosur','Paraguay','PY',18),
('YT','TGA','Air Togo','Togo','TG',18),
('FS','STU','Servicios de Transportes A','Argentina','AR',17),
('HZ','SOZ','Sat Airlines','Kazakhstan','KZ',17),
('K3','\N','Atlantic Air Cargo','United States','US',17),
('RZ',null,'Euro Exec Express','Sweden','SE',17),
('TN','THT','Air Tahiti Nui','France','FR',17),
('DX','DTR','DAT Danish Air Transport','Denmark','DK',16),
('ID','ITK','Interlink Airlines','South Africa','ZA',16),
('LC','VLO','Varig Log','Brazil','BR',16),
('NP','NIA','Nile Air','Egypt','EG',16),
('P9',null,'Nas Air','Mali','ML',16),
('PM','TOS','Tropic Air','Belize','BZ',16),
('QN','ARR','Air Armenia','Armenia','AM',16),
('RI','MDL','Mandala Airlines','Indonesia','ID',16),
('T5','TUA','Turkmenistan Airlines','Turkmenistan','TM',16),
('TW','TWA','Trans World Airlines','United States','US',16),
('U7','UGD','Uganda Airlines','Uganda','UG',16),
('UE','NAS','Nasair','Eritrea','ER',16),
('J5','\N','Alaska Seaplane Service','United States','US',15),
('P2','XAK','AirKenya Express','Kenya','KE',15),
('S5','TCF','Shuttle America','United States','US',15)
on conflict (iata) do update set icao=excluded.icao,name=excluded.name,country=excluded.country,country_code=excluded.country_code,route_count=excluded.route_count;

insert into public.airlines (iata,icao,name,country,country_code,route_count) values
('2L','OAW','Helvetic Airways','Switzerland','CH',14),
('4Q','\N','Safi Airlines','Afghanistan','AF',14),
('F2','FLM','Fly Air','Turkey',null,14),
('MN','LNK','Airlink','South Africa','ZA',14),
('PI','PDT','Piedmont Airlines (1948-1989)','United States','US',14),
('Q7','\N','SkyBahamas Airlines','Bahamas','BS',14),
('Q8','PEC','Pacific East Asia Cargo Airlines','Philippines','PH',14),
('QL','RLN','Aero Lanka','Sri Lanka','LK',14),
('TA','TAT','Grupo TACA','Costa Rica','CR',14),
('TJ','\N','Transportes Aéreos Nacionales de Selva','Peru','PE',14),
('W4','BES','Aero Services Executive','France','FR',14),
('XL','LNE','Aerolane','Ecuador','EC',14),
('YQ','\N','Polet Airlines (Priv)','Russia',null,14),
('4N','ANT','Air North Charter - Canada','Canada','CA',13),
('CC','ABD','Air Atlanta Icelandic','Iceland','IS',13),
('DH','DVA','Discovery Airways','United States','US',13),
('GZ','RAR','Air Rarotonga','Cook Islands','CK',13),
('M6','AJT','Amerijet International','United States','US',13),
('2K','GLG','Aerolineas Galapagos (Aerogal)','Ecuador','EC',12),
('3F','3FF','Fly Colombia ( Interliging Flights )','Colombia','CO',12),
('4T','BHP','Belair Airlines','Switzerland','CH',12),
('6H','ISR','Israir','Israel','IL',12),
('8B','GFI','Caribbean Star Airlines','Antigua and Barbuda','AG',12),
('8M','MXL','Maxair','Sweden','SE',12),
('E2','KMP','Kampuchea Airlines','Cambodia','KH',12),
('EN','DLA','Air Dolomiti','Italy','IT',12),
('EO','LHN','Express One International','United States','US',12),
('LT','LTU','LTU International','Germany','DE',12),
('OM','MGL','MIAT Mongolian Airlines','Mongolia','MN',12),
('QB','GFG','Georgian National Airlines','Georgia','GE',12),
('UM','AZW','Air Zimbabwe','Zimbabwe','ZW',12),
('VH','VNP','Virgin Pacific','Fiji','FJ',12),
('Z3','SMJ','Avient Aviation','Zimbabwe','ZW',12),
('TE','LIL','FlyLal','Lithuania','LT',11),
('2O',null,'Air Salone','Sierra Leone','SL',10),
('3E','\N','Air Choice One','United States','US',10),
('4M','DSM','LAN Argentina','Argentina','AR',10),
('6W','SOV','Saratov Aviation Division','Russia',null,10),
('8T',null,'Air Tindi','Canadian Territories',null,10),
('A2','CIU','Cielos Airlines','Peru','PE',10),
('CE','NTW','Nationwide Airlines','South Africa','ZA',10),
('CN',null,'Islands Nationair','Papua New Guinea','PG',10),
('E5','BRZ','Samara Airlines','Russia',null,10),
('HM','SEY','Air Seychelles','Seychelles','SC',10),
('HW','FHE','Hello','Switzerland','CH',10),
('JA','BON','Air Bosna','Bosnia and Herzegovina','BA',10),
('LW','NMI','Pacific Wings','United States','US',10),
('NY','FXI','Air Iceland','Iceland','IS',10),
('RG','VRN','VRG Linhas Aereas','Brazil','BR',10),
('SH','FLY','Fly Me Sweden','Sweden','SE',10),
('V9','BTC','BAL Bashkirian Airlines','Russia',null,10),
('WW','BMI','bmibaby','United Kingdom','GB',10),
('Z4','OOM','Zoom Airlines','Canada','CA',10),
('R2','ORB','Orenburg Airlines','Russia',null,9),
('RC','FLI','Atlantic Airways','Faroe Islands','FO',9),
('RL','RFJ','Royal Falcon','Jordan','JO',9),
('7M','ZTF','Mongolian International Air Lines','Mongolia','MN',8),
('8D',null,'Astair','Russian Federation','RU',8),
('BH',null,'Hawkair','Canada','CA',8),
('C8','WDY','Chicago Express','United States','US',8),
('EF','EFA','Far Eastern Air Transport','Taiwan',null,8),
('I8','\N','IzAvia','Russia',null,8),
('J4','BFL','Buffalo Airways','Canada','CA',8),
('JN','XLA','Excel Airways','United Kingdom','GB',8),
('JS','KOR','Air Koryo','Democratic People''s Republic of Korea',null,8),
('JW','APW','Arrow Air','United States','US',8),
('K8','ZAK','Airlink Zambia','Zambia','ZM',8),
('OC','\N','Catovair','Mauritius','MU',8),
('OJ','OLA','Overland Airways','Nigeria','NG',8),
('ON','RON','Nauru Air Corporation','Nauru','NR',8),
('RA','RNA','Nepal Airlines','Nepal','NP',8),
('S9','HSA','East African Safari Air','Kenya','KE',8),
('VQ','VKH','Viking Hellas','Greece','GR',8),
('Z9','\N','Flightlink Tanzania','Tanzania',null,8),
('5Z','BML','Bismillah Airlines','Bangladesh','BD',7),
('3P','TNM','Tiara Air','Aruba','AW',6),
('7G','SFJ','Star Flyer','Japan','JP',6),
('8I',null,'Myway Airlines','Italy','IT',6),
('AW','AFW','Africa World Airlines','Ghana','GH',6),
('D3','DAO','Daallo Airlines','Djibouti','DJ',6),
('E8','ELG','Alpi Eagles','Italy','IT',6),
('EL','ANK','Air Nippon','Japan','JP',6),
('HK','FSC','Four Star Aviation / Four Star Cargo','United States','US',6),
('HN','HVY','Heavylift Cargo Airlines','Australia','AU',6),
('M3','TUS','ABSA - Aerolinhas Brasileiras','Brazil','BR',6),
('M9','MSI','Motor Sich','Ukraine','UA',6),
('OX','OEA','Orient Thai Airlines','Thailand','TH',6),
('PJ','SPM','Air Saint Pierre','France','FR',6),
('PQ','PNF','Panafrican Airways','Ivory Coast',null,6),
('PV','PNR','PAN Air','Spain','ES',6),
('S3','BBR','Santa Barbara Airlines','Venezuela',null,6),
('S6',null,'Star Air','Denmark','DK',6),
('V3','KRP','Carpatair','Romania','RO',6),
('VF','VLU','Valuair','Singapore','SG',6),
('WP','MKU','Island Air (WP)','United States','US',6),
('XV','\N','BVI Airways','British Virgin Islands',null,6),
('3J','WZP','Zip','Canada','CA',5),
('F5','COZ','Cosmic Air','Nepal','NP',5),
('FV','SDM','Rossiya-Russian Airlines','Russia',null,5),
('RQ','KMF','Kam Air','Afghanistan','AF',5),
('5P','\N','Pal airlines','Chile','CL',4),
('9Q','PBA','PB Air','Thailand','TH',4),
('A8','BGL','Benin Golf Air','Benin','BJ',4),
('BF','RSR','Aero-Service','Republic of the Congo',null,4),
('DZ','\N','Starline.kz','Kazakhstan','KZ',4),
('E7','ESF','Estafeta Carga Aerea','Mexico','MX',4),
('E9','CXS','Boston-Maine Airways','United States','US',4),
('I9','AEY','Air Italy','Italy','IT',4),
('J8','BVT','Berjaya Air','Malaysia','MY',4),
('LF','NDC','FlyNordic','Sweden','SE',4),
('LV','LBC','Albanian Airlines','Albania','AL',4),
('N3','OMS','Omskavia Airline','Russia',null,4),
('OY','OAE','Omni Air International','United States','US',4),
('Q5','MLA','40-Mile Air','United States','US',4),
('QU','UGX','East African','Uganda','UG',4),
('TD','LUR','Atlantis European Airways','Armenia','AM',4),
('UY','UYC','Cameroon Airlines','Cameroon','CM',4),
('Y5','PCE','Pace Airlines','United States','US',4),
('YO','TYS','TransHolding System','Brazil','BR',4),
('ZM','ZAW','Zambia Airways','Zambia','ZM',4),
('4B','BTQ','Boutique Air (Priv)','United States','US',2),
('4D','ASD','Air Sinai','Egypt','EG',2),
('4K','AAS','Askari Aviation','Pakistan','PK',2),
('5G','SSV','Skyservice Airlines','Canada','CA',2),
('5M','SIB','Sibaviatrans','Russia',null,2),
('6I','IBZ','International Business Air','Sweden','SE',2),
('6Y','\N','SmartLynx Airlines','Latvia','LV',2),
('7E','AWU','Aeroline GmbH','Germany','DE',2),
('D6','ILN','Interair South Africa','South Africa','ZA',2),
('GY',null,'Guyana Airways 2000',null,null,2),
('H7',null,'Eagle Air','Uganda','UG',2),
('HI','\N','Papillon Grand Canyon Helicopters','United States','US',2),
('HR','CUA','China United Airlines','China','CN',2),
('I4','FWA','Interstate Airline','Netherlands','NL',2),
('JB','JBA','Helijet','Canada','CA',2),
('KO','AER','Alaska Central Express','United States','US',2),
('PE','AEL','Air Europe','Italy','IT',2),
('Q3','MBN','Zambian Airways','Zambia','ZM',2),
('UD','HER','Hex''Air','France','FR',2),
('V4','REK','Reem Air','Kyrgyzstan','KG',2),
('X7','CHF','Chitaavia','Russia',null,2),
('YR','\N','SENIC AIRLINES','United States','US',2),
('EW','EWG','Eurowings','Germany','DE',1),
('FA','SFR','FlySafair','South Africa','ZA',1),
('JM','JMA','Jambojet','Kenya','KE',1),
('MA','MWI','Malawi Airlines','Malawi','MW',1),
('RE','RND','Renegade Air','Kenya','KE',1),
('TC','ATC','Air Tanzania','Tanzania','TZ',1),
('VL','VIM','Air VIA','Nigeria','NG',1),
('&T','T&O','Tom\\''s & co airliners','France','FR',0),
('-+','--+','U.S. Air','United States','US',0),
('--','ELK','ELK Airways','Estonia','EE',0),
('..','...','Avilu','Switzerland','CH',0),
('01','\N','Bobb Air Freight','Germany','DE',0),
('0B','JOR','Blue Air','Romania','RO',0),
('0D','DWT','Darwin Airline','Switzerland','CH',0),
('0G','GA0','Global Airlines','Argentina','AR',0),
('0M','0MM','All America MX','Mexico','MX',0),
('0P','PYB','All America BOPY','Paraguay','PY',0),
('0X','CX0','Copenhagen Express','Denmark','DK',0),
('0Y','7ZC','All America CO','Colombia','CO',0),
('11','\N','TUIfly (X3)','Germany','DE',0),
('12','N12','12 North','India','IN',0),
('13','EAV','Eastern Atlantic Virtual Airlines','United States','US',0),
('1B',null,'Abacus International','Singapore','SG',0),
('1C','1CH','OneChina','China','CN',0),
('1E','RGG','TransRussiaAirlines','Russia',null,0),
('1F','CIF','CB Airways UK ( Interliging Flights )','United Kingdom','GB',0),
('1I','EJA','NetJets','United States','US',0),
('1K','BG1','BudgetAir','Germany','DE',0),
('1R','R1R','All America CL','Chile','CL',0),
('1T','RNX','1Time Airline','South Africa','ZA',0),
('1X','\N','Island Express Air','Canada','CA',0),
('1Y','A9B','All America BR','Brazil','BR',0),
('20','RNE','Air Salone','Sierra Leone','SL',0),
('24','\N','Euro Jet','Germany','DE',0),
('2A',null,'Deutsche Bahn','Germany','DE',0),
('2D','\N','Aero VIP (2D)','Portugal','PT',0),
('2F','FTA','Frontier Flying Service','United States','US',0),
('2M','MDV','Moldavian Airlines','Moldova',null,0),
('2Q','SNC','Air Cargo Carriers','United States','US',0),
('2R','M7A','All America AR','Argentina','AR',0),
('2S','\N','Air Carnival','India','IN',0),
('2T','HAM','Haiti Ambassador Airlines','Haiti','HT',0),
('2U','GIP','Air Guinee Express','Guinea','GN',0),
('2W','WLC','Welcome Air','Austria','AT',0),
('2X','2K2','Regionalia Uruguay','Uruguay','UY',0),
('3B','\N','JobAir','Czech Republic',null,0),
('3I','\N','Air Comet Chile','Chile','CL',0),
('3Q','CYH','Yunnan Airlines','China','CN',0),
('3T','URN','Turan Air','Azerbaijan','AZ',0),
('3W','\N','Malawian Airlines','Malawi','MW',0),
('47','VVN','88','Cyprus','CY',0),
('4A','AKL','Air Kiribati','Kiribati','KI',0),
('4C','ARE','Aires','S.A.',null,0),
('4L','MJX','Euroline','Georgia','GE',0),
('4P','\N','Business Aviation','Congo (Kinshasa)',null,0),
('4R','HHI','Hamburg International','Germany','DE',0),
('4S','VI4','Vuola Italia','Italy','IT',0),
('4X','\N','Red Jet Mexico','Mexico','MX',0),
('4Z','\N','Airlink (SAA)','South Africa','ZA',0),
('5B','BSX','Bassaka airlines','Cambodia','KH',0),
('5D','SLI','Aerolitoral','Mexico','MX',0),
('5E','\N','SGA Airlines','Thailand','TH',0),
('5K','\N','Hi Fly (5K)','Portugal','PT',0),
('5L','RSU','Aerosur','Bolivia',null,0),
('5W','AEU','Astraeus','United Kingdom','GB',0),
('5Y','GTI','Atlas Air','United States','US',0),
('69','\N','Royal European Airlines','United Kingdom','GB',0),
('6A','CHP','Consorcio Aviaxsa','Mexico','MX',0),
('6B','BLX','TUIfly Nordic','Sweden','SE',0),
('6C','6CC','Vuela Cuba','Cuba','CU',0),
('6D','\N','Pelita','Indonesia','ID',0),
('6F','MKD','MAT Airways','Macedonia',null,0),
('6G','AWW','Air Wales','United Kingdom','GB',0),
('6J','SNJ','Skynet Asia Airways','Japan','JP',0),
('6K','RIT','Asian Spirit','Philippines','PH',0),
('6P','\N','Gryphon Airlines','United States','US',0),
('6U','\N','Air Cargo Germany','Germany','DE',0),
('6V','CZV','Via Conectia Airlines','Uruguay','UY',0),
('76','SJS','Southjet','United States','US',0),
('77','ZCS','Southjet connect','United States','US',0),
('78','XAN','Southjet cargo','United States','US',0),
('7B','KJC','Krasnojarsky Airlines','Russia',null,0),
('7K','KGL','Kogalymavia Air Company','Russia',null,0),
('7L','ERO','Sun D''Or','Israel','IL',0),
('7O','7KK','All Colombia','Colombia','CO',0),
('7Q','\N','Pan Am World Airways Dominicana','Dominican Republic','DO',0),
('7T','AGV','Air Glaciers','Switzerland','CH',0),
('7W',null,'Wayraper','Peru','PE',0),
('7Y','\N','Med Airways','Lebanon','LB',0),
('7Z','\N','Halcyonair','Cape Verde',null,0),
('88','8K8','All Australia','Australia','AU',0),
('8A','BMM','Atlas Blue','Morocco','MA',0),
('8F','STP','STP Airways','Sao Tome and Principe','ST',0),
('8H','HFR','Heli France','France','FR',0),
('8J','JFU','Jet4You','Morocco','MA',0),
('8K','K88','Voestar','Brazil','BR',0),
('8N','NKF','Barents AirLink','Sweden','SE',0),
('8O',null,'West Coast Air','Canada','CA',0),
('8Z','WVL','Wizz Air Hungary','Bulgaria','BG',0),
('99','\N','Ciao Air','Italy','IT',0),
('9A','99F','All Africa','South Africa','ZA',0),
('9H','\N','MDLR Airlines','India','IN',0),
('9I','INE','International Europe','Spain','ES',0),
('9J','CR1','Regionalia Chile','Chile','CL',0),
('9L','CJC','Colgan Air','United States','US',0),
('9S','CQH','Spring Airlines','China','CN',0),
('9T','ABS','Transwest Air','Canada','CA',0),
('9X','9XX','Regionalia Venezuela','Venezuela',null,0),
('9Y','KZK','Air Kazakhstan','Kazakhstan','KZ',0),
(';;','\N','Wilderness Air','Australia','AU',0),
('A1','A1F','Atifly','United States','US',0),
('A6','\N','Air Alps Aviation (A6)','Austria','AT',0),
('A7','MPD','Air Plus Comet','Spain','ES',0),
('AG','SSA','All America US','United States','US',0),
('AJ','NIG','Aero Contractors','Nigeria','NG',0),
('AL','SYX','Skywalk Airlines','United States','US',0),
('AN','AAA','Ansett Australia','Australia','AU',0),
('AO','\N','Avianova (Russia)','Russia',null,0),
('AQ','AAH','Aloha Airlines','United States','US',0),
('AU','AUT','Austral Lineas Aereas','Argentina','AR',0),
('AX','LOF','Trans States Airlines','United States','US',0),
('B0','666','Aws express','United States','US',0),
('B1','BA1','Baltic Air lines','Latvia','LV',0),
('B3','BLV','Bellview Airlines','Nigeria','NG',0),
('B4','GSM','Flyglobespan','United Kingdom','GB',0),
('B8','ERT','Eritrean Airlines','Eritrea','ER',0),
('BD','BMA','bmi','United Kingdom','GB',0),
('BN','HZA','Horizon Airlines','Australia','AU',0),
('BQ','BQB','Buquebus Líneas Aéreas','Uruguay','UY',0),
('BS','BIH','British International Helicopters','United Kingdom','GB',0),
('BY','TOM','Thomsonfly','United Kingdom','GB',0),
('BZ','BSA','Black Stallion Airways','United States','US',0),
('C0','CLW','Centralwings','Poland','PL',0),
('C1','CA1','CanXpress','Canada','CA',0),
('C2','CAP','CanXplorer','Canada','CA',0),
('C3','KIS','Contact Air','Germany','DE',0),
('C4','LIX','LionXpress','Cameroon','CM',0),
('C5','UCA','CommutAir','United States','US',0),
('C7','CR7','Sky Wing Pacific','South Korea',null,0),
('C9','RUS','Cirrus Airlines','Germany','DE',0),
('CB','CCC','CCML Airlines','Colombia','CO',0),
('CD','\N','Air India Regional','India','IN',0),
('CF','SDR','City Airline','Sweden','SE',0),
('CH','BMJ','Bemidji Airlines','United States','US',0),
('CJ','CFE','BA CityFlyer','United Kingdom','GB',0),
('CL','CLH','Lufthansa CityLine','Germany','DE',0),
('CO','COA','Continental Airlines','United States','US',0),
('CP','CDN','Canadian Airlines','Canada','CA',0),
('CQ','KOL','SOCHI AIR','Russia',null,0),
('CS','CMI','Continental Micronesia','United States','US',0),
('CT','\N','Alitalia Cityliner','Italy','IT',0),
('CV','CVA','Air Chathams','New Zealand','NZ',0),
('CW','CWM','Air Marshall Islands','Marshall Islands','MH',0),
('D1','MDO','Domenican Airlines','Dominican Republic','DO',0),
('D8','DJB','Djibouti Airlines','Djibouti','DJ',0),
('D9','DNV','Aeroflot-Don','Russia',null,0),
('DA','\N','Dana Air','Nigeria','NG',0),
('DB','BZH','Brit Air','France','FR',0),
('DF','MJG','Michael Airlines','Puerto Rico','PR',0),
('DI','BAG','dba','Germany','DE',0),
('DK','ELA','Eastland Air','Australia','AU',0),
('DM',null,'Maersk','Denmark','DK',0),
('DO','DOA','Dominicana de Aviaci','Dominican Republic','DO',0),
('DP','FCA','First Choice Airways','United Kingdom','GB',0),
('DQ',null,'Coastal Air','United States','US',0),
('DR','BIE','Air Mediterranee','France','FR',0),
('DS','\N','EasyJet (DS)','Switzerland','CH',0),
('DU','NLH','Norwegian Long Haul AS','Norway','NO',0),
('E1','ES2','Usa Sky Cargo','United States','US',0),
('E3','DMO','Domodedovo Airlines','Russia',null,0),
('E4','GIE','Elysian Airlines','Cameroon','CM',0),
('EA','EAL','European Air Express','Germany','DE',0),
('EC','TWN','Avialeasing Aviation Company','Uzbekistan','UZ',0),
('ED','ABQ','Airblue','Pakistan','PK',0),
('EE','\N','Nordica','Estonia','EE',0),
('EJ','NEA','New England Airlines','United States','US',0),
('EM','AEB','Aero Benin','Benin','BJ',0),
('ER','RWW','Fly Europa','Spain','ES',0),
('ES','EUV','EuropeSky','Germany','DE',0),
('EV','ASQ','Atlantic Southeast Airlines','United States','US',0),
('EX','EU9','Europe Jet','France','FR',0),
('EZ','EIA','Evergreen International Airlines','United States','US',0),
('F1','FBL','Fly Brasil','Brazil','BR',0),
('F8','\N','Air2there','New Zealand','NZ',0),
('FC','WBA','Finncomm Airlines','Finland','FI',0),
('FF','FRF','Fly France','France','FR',0),
('FH','FHI','FlyHigh Airlines Ireland (FH)','Ireland','IE',0),
('FK','WTA','Africa West','Togo','TG',0),
('FN',null,'Regional Airlines','Morocco','MA',0),
('FP','FRE','Freedom Air','United States','US',0),
('FQ','TCW','Thomas Cook Airlines','Belgium','BE',0),
('FT','SRH','Siem Reap Airways','Cambodia','KH',0),
('FU','FXX','Felix Airways','Yemen','YE',0),
('FX','FOX','FOX Linhas Aereas','Brazil','BR',0),
('G0','GHB','Ghana International Airlines','Ghana','GH',0),
('G1','IG1','Indya Airline Group','India','IN',0),
('G6','\N','Air Volga','Russia',null,0),
('G7','GJS','GoJet Airlines','United States','US',0),
('GB','BZE','BRAZIL AIR','Brazil','BR',0),
('GG','GUY','Air Guyane','French Guiana','GF',0),
('GH','GLP','Globus','Russia',null,0),
('GI','IKA','Itek Air','Kyrgyzstan','KG',0),
('GJ','EEU','Eurofly Service','Italy','IT',0),
('GM','GER','German International Air Lines','Germany','DE',0),
('GN','\N','GNB Linhas Aereas','Brazil','BR',0),
('GO','KZU','Kuzu Airlines Cargo','Turkey',null,0),
('GP','GDR','Gadair European Airlines','Spain','ES',0),
('GT','GBL','GB Airways','United Kingdom','GB',0),
('GW','KIL','Kuban Airlines','Russia',null,0),
('GX','GXG','GermanXL','Germany','DE',0),
('H1','HA1','Hankook Air US','United States','US',0),
('H3','\N','Harbour Air (Priv)','Canada','CA',0),
('H5','RSY','I-Fly','Russia',null,0),
('H6','HAG','Hageland Aviation Services','United States','US',0),
('H8','KHB','Dalavia','Russia',null,0),
('H9','\N','PEGASUS AIRLINES-','Turkey',null,0),
('HC','HYM','Himalayan Airlines','Nepal','NP',0),
('HE','LGW','Luftfahrtgesellschaft Walter','Germany','DE',0),
('HH','AHO','Air Hamburg (AHO)','Germany','DE',0),
('HP','AWE','America West Airlines','United States','US',0),
('HT','IMP','Hellenic Imperial Airways','Greece','GR',0),
('I2','IBS','Iberia Express','Spain','ES',0),
('I3','\N','ATA Airlines (Iran)','Iran',null,0),
('I5','IDS','Indonesia Sky','Indonesia','ID',0),
('I7','PMW','Paramount Airways','India','IN',0),
('IA','IAW','Iraqi Airways','Iraq','IQ',0),
('IC','IAC','Indian Airlines','India','IN',0),
('IF','ISW','Islas Airways','Spain','ES',0),
('II','UWW','LSM International','Russia',null,0),
('IJ','SJO','Spring Airlines Japan','Japan','JP',0),
('IK','ITX','Imair Airlines','Azerbaijan','AZ',0),
('IN','MAK','MAT Macedonian Airlines','Macedonia',null,0),
('IO','IAA','Indonesian Airlines','Indonesia','ID',0),
('IP','ISX','Island Spirit','Iceland','IS',0),
('IQ','AUB','Augsburg Airways','Germany','DE',0),
('IS',null,'Island Airlines','United States','US',0),
('IT','KFR','Kingfisher Airlines','India','IN',0),
('IV','JET','Wind Jet','Italy','IT',0),
('IW','WON','Wings Air','Indonesia','ID',0),
('J1','\N','OneJet','United States','US',0),
('J7','\N','Denim Air','Norway','NO',0),
('JC','JEX','JAL Express','Japan','JP',0),
('JF','JAF','Jetairfly','Belgium','BE',0),
('JG','\N','Jetgo Australia','Australia','AU',0),
('JI','MDW','Midway Airlines','United States','US',0),
('JK','JKK','Spanair','Spain','ES',0),
('JO','JAZ','JALways','Japan','JP',0),
('JR','JOY','Joy Air','China','CN',0),
('JX','JSR','Jusur airways','Egypt','EG',0),
('JZ','SKX','Skyways Express','Sweden','SE',0),
('K1','KOQ','Kostromskie avialinii','Russia',null,0),
('K7','KBR','KoralBlue Airlines','Egypt','EG',0),
('KD','KNI','KD Avia','Russia',null,0),
('KF','BLF','Blue1','Finland','FI',0),
('KG','RAW','Royal Airways','United States','US',0),
('KH','KHK','Kharkiv Airlines','Ukraine','UA',0),
('KI','DHI','Adam Air','Indonesia','ID',0),
('KJ','LAJ','British Mediterranean Airways','United Kingdom','GB',0)
on conflict (iata) do update set icao=excluded.icao,name=excluded.name,country=excluded.country,country_code=excluded.country_code,route_count=excluded.route_count;

insert into public.airlines (iata,icao,name,country,country_code,route_count) values
('KP','DWA','Dense Airways','United States','US',0),
('KT','VKJ','VickJet','France','FR',0),
('KV','MVD','Kavminvodyavia','Russia',null,0),
('KW','\N','Carnival Air Lines','United States','US',0),
('KZ','DC2','Dense Connection','United States','US',0),
('L1','AL1','All Argentina','Argentina','AR',0),
('L3','LTO','LTU Austria','Austria','AT',0),
('L4','LJJ','Luchsh Airlines','Russia',null,0),
('L5','LTR','Lufttransport','Norway','NO',0),
('L7','\N','Lugansk Airlines','Ukraine','UA',0),
('L8','LBL','Line Blue','Germany','DE',0),
('L9','AL3','All Asia','China','CN',0),
('LB','\N','Air Costa','India','IN',0),
('LE','LTY','Liberty Airways','United States','US',0),
('LK','LXR','Air Luxor','Portugal','PT',0),
('LP','LPE','LAN Peru','Peru','PE',0),
('LQ','LMM','LCM AIRLINES','Russia',null,0),
('LU','LXP','LAN Express','Chile','CL',0),
('LZ',null,'Balkan Bulgarian Airlines',null,null,0),
('M1','M1F','Maryland Air','United States','US',0),
('M2','\N','MHS Aviation GmbH','Germany','DE',0),
('M7','MAA','MasAir','Mexico','MX',0),
('M8','TNU','TransNusa Air','Indonesia','ID',0),
('MB','MNB','MNG Airlines','Turkey',null,0),
('ML','MAV','Maldivo Airlines','Maldives','MV',0),
('MP','MPH','Martinair','Netherlands','NL',0),
('MQ','EGF','American Eagle Airlines','United States','US',0),
('MT','TCX','Thomas Cook Airlines','United Kingdom','GB',0),
('MX','MXA','Mexicana de Aviaci','Mexico','MX',0),
('MZ','MNA','Merpati Nusantara Airlines','Indonesia','ID',0),
('N0','\N','Norte Lineas Aereas','Argentina','AR',0),
('N1','\N','N1','Peru','PE',0),
('N4','J88','Regionalia México','Mexico','MX',0),
('N5','SGY','Skagway Air Service','United States','US',0),
('N7','N77','All Spain','Spain','ES',0),
('N8','NCR','National Air Cargo','United States','US',0),
('N9','N99','All Europe','United Kingdom','GB',0),
('NA','\N','Al-Naser Airlines','Iraq','IQ',0),
('NB','SNB','Sterling Airlines','Denmark','DK',0),
('NC','NJS','National Jet Systems','Australia','AU',0),
('NE','ESK','SkyEurope','Slovakia','SK',0),
('NG','LDA','Lauda Air','Austria','AT',0),
('NI','PGA','Portugalia','Portugal','PT',0),
('NJ','NGB','Nordic Global Airlines','Finland','FI',0),
('NM','DRD','Air Madrid','Spain','ES',0),
('NN','MOV','VIM Airlines','Russia',null,0),
('NQ','AJX','Air Japan','Japan','JP',0),
('NR','JTO','Jettor Airlines','Hong Kong','HK',0),
('NW','NWA','Northwest Airlines','United States','US',0),
('O1','OAB','Orbit Airlines Azerbaijan','Azerbaijan','AZ',0),
('O2',null,'Oceanic Airlines','Guinea','GN',0),
('O7','OZJ','Ozjet Airlines','Australia','AU',0),
('O8','OHK','Oasis Hong Kong Airlines','Hong Kong','HK',0),
('OF','FIF','Air Finland','Finland','FI',0),
('OG','\N','AirOnix','Ukraine','UA',0),
('OH','COM','Comair','United States','US',0),
('OI','ORC','Orchid Airlines','Australia','AU',0),
('OL','OLT','Ostfriesische Lufttransport','Germany','DE',0),
('OO','SKW','SkyWest','United States','US',0),
('OP','PPL','Air Pegasus','India','IN',0),
('OQ','CQN','Chongqing Airlines','China','CN',0),
('OT','PEL','Aeropelican Air Services','Australia','AU',0),
('P5','RPB','AeroRep','Colombia','CO',0),
('P7','REP','Regional Paraguaya','Paraguay','PY',0),
('P8','MKG','Air Mekong','Vietnam',null,0),
('PA','IPV','Parmiss Airlines (IPV)','Iran',null,0),
('PF','\N','Primera Air','Iceland','IS',0),
('PH','PAO','Polynesian Airlines','Samoa','WS',0),
('PO','FPT','FlyPortugal','Portugal','PT',0),
('PP','AI0','Air Indus','Pakistan','PK',0),
('PT','\N','Red Jet Andes','Peru','PE',0),
('PU','PUA','PLUNA','Uruguay','UY',0),
('Q4','SAE','SOCHI AIR EXPRESS','Russia',null,0),
('QA','\N','Click (Mexicana)','Mexico','MX',0),
('QD','DOB','Dobrolet','Russia',null,0),
('QI','CIM','Cimber Air','Denmark','DK',0),
('QJ',null,'Jet Airways','United States','US',0),
('QK','JZA','Air Canada Jazz','Canada','CA',0),
('QM','AML','Air Malawi','Malawi','MW',0),
('QO','OGN','Origin Pacific Airways','New Zealand','NZ',0),
('QP','\N','Air Kenya (Priv)','Kenya','KE',0),
('QQ','UTY','Alliance Airlines','Australia','AU',0),
('QT','TPA','TAMPA','Colombia','CO',0),
('QW','BWG','Blue Wings','Germany','DE',0),
('QX','QXE','Horizon Air','United States','US',0),
('QY','\N','Red Jet Canada','Canada','CA',0),
('R4',null,'Rossiya','Russia',null,0),
('R5','MAC','Malta Air Charter','Malta','MT',0),
('R6',null,'RACSA','Guatemala','GT',0),
('R8','RRJ','AirRussia','Russia',null,0),
('RB','SYR','Syrian Arab Airlines','Syrian Arab Republic','SY',0),
('RD','RYN','Ryan International Airlines','United States','US',0),
('RF','FWL','Florida West International Airways','United States','US',0),
('RH','RPH','Republic Express Airlines','Indonesia','ID',0),
('RK','RKA','Air Afrique','Ivory Coast',null,0),
('RM','RNY','Rainbow Air US','United States','US',0),
('RN','RAB','Rainbow Air (RAI)','United States','US',0),
('RP','CHQ','Chautauqua Airlines','United States','US',0),
('RR','RXR','REXAIR VIRTUEL','France','FR',0),
('RS','SKV','Sky Regional','Canada','CA',0),
('RT','\N','Real Tonga','Tonga','TO',0),
('RU','RUE','Rainbow Air Euro','United Kingdom','GB',0),
('RV','CPN','Caspian Airlines','Iran',null,0),
('RW','RPA','Republic Airlines','United States','US',0),
('RY','RAY','Rainbow Air Canada','Canada','CA',0),
('S0','SAL','Spike Airlines','United States','US',0),
('S1','SA1','Serbian Airlines','Serbia','RS',0),
('S8','SBD','Snowbird Airlines','Finland','FI',0),
('SL','\N','Thai Lion Air','Thailand','TH',0),
('SM','MNP','Spirit of Manila Airlines','Philippines','PH',0),
('SO','SLC','Salsa d\\''Haiti','Haiti','HT',0),
('SR','SWR','Swissair','Switzerland','CH',0),
('T0','\N','TACA Peru','Peru','PE',0),
('T2','TCG','Thai Air Cargo','Thailand','TH',0),
('T4','HEJ','Hellas Jet','Greece','GR',0),
('T6','TP6','Trans Pas Air','United States','US',0),
('TB','TBZ','TrasBrasil','Brazil','BR',0),
('TH','THS','TransBrasil Airlines','Brazil','BR',0),
('TI','THI','TransHolding','Brazil','BR',0),
('TQ','TXW','Texas Wings','United States','US',0),
('U1','ABI','Aviabus','Russia',null,0),
('U3','AIA','Avies','Estonia','EE',0),
('U4','PMT','PMTair','Cambodia','KH',0),
('U5','GWY','USA3000 Airlines','United States','US',0),
('U8','RNV','Armavia','Armenia','AM',0),
('U9','TAK','Tatarstan Airlines','Russia',null,0),
('UB','UBA','Myanma Airways','Myanmar','MM',0),
('UF','UKM','UM Airlines','Ukraine','UA',0),
('UH',null,'US Helicopter Corporation','United States','US',0),
('UI','ECA','Eurocypria Airlines','Cyprus','CY',0),
('UK','VTI','Air Vistara','India','IN',0),
('UQ','SJU','Skyjet Airlines','Uganda','UG',0),
('UT','UTA','UTair Aviation','Russia',null,0),
('UW','\N','UVT Aero','Russia',null,0),
('UZ','BRQ','El-Buraq Air Transport','Libya','LY',0),
('V1','VIA','VIA Líneas Aéreas','Argentina','AR',0),
('V2','RBY','Vision Airlines (V2)','United States','US',0),
('V5','\N','Danube Wings (V5)','Slovakia','SK',0),
('V6','\N','VIP Ecuador','Ecuador','EC',0),
('V8','VAS','ATRAN Cargo Airlines','Russian Federation','RU',0),
('VC','\N','Strategic Airlines','Australia','AU',0),
('VD',null,'Air Libert','France','FR',0),
('VE','VLE','Volare Airlines','Italy','IT',0),
('VG','VLM','VLM Airlines','Belgium','BE',0),
('VI','VDA','Volga-Dnepr Airlines','Russia',null,0),
('VK','VGN','Virgin Nigeria Airways','Nigeria','NG',0),
('VO','TYR','Tyrolean Airways','Austria','AT',0),
('VP','VSP','VASP','Brazil','BR',0),
('VU','VUN','Air Ivoire','Ivory Coast',null,0),
('VV','AEW','Aerosvit Airlines','Ukraine','UA',0),
('VZ','MYT','MyTravel Airways','United Kingdom','GB',0),
('W1','WE1','World Experience Airline','Canada','CA',0),
('W7','\N','Austral Brasil','Brazil','BR',0),
('WA','KLC','KLM Cityhopper','Netherlands','NL',0),
('WC','ISV','Islena De Inversiones','Honduras','HN',0),
('WD','AAN','Amsterdam Airlines','Netherlands','NL',0),
('WE','\N','Thai Smile Airways','Thailand','TH',0),
('WG','\N','Sunwing','Canada','CA',0),
('WH','\N','China Northwest Airlines (WH)','China','CN',0),
('WK','EDW','Edelweiss Air','Switzerland','CH',0),
('WO','WOA','World Airways','United States','US',0),
('WQ','PQW','PanAm World Airways','United States','US',0),
('WR','WEN','WestJet Encore','Canada','CA',0),
('WV','SWV','Swe Fly','Sweden','SE',0),
('WZ','RWZ','Red Wings','Russia',null,0),
('X5','OTJ','Fly Romania','Romania','RO',0),
('XA','XAU','XAIR USA','United States','US',0),
('XB','NXB','NEXT Brasil','Brazil','BR',0),
('XE','BTA','ExpressJet','United States','US',0),
('XF','VLK','Vladivostok Air','Russia',null,0),
('XG','CLI','Calima Aviacion','Spain','ES',0),
('XJ','MES','Mesaba Airlines','United States','US',0),
('XM','SMX','Alitalia Express','Italy','IT',0),
('XN','\N','Xpressair','Indonesia','ID',0),
('XO','LTE','LTE International Airways','Spain','ES',0),
('XP','XPT','XPTO','Portugal','PT',0),
('XR','\N','Skywest Australia','Australia','AU',0),
('XT','AXL','Air Exel','Netherlands','NL',0),
('XW','SXR','Sky Express','Russia',null,0),
('XX','GFY','Greenfly','Spain','ES',0),
('XZ','\N','Congo Express','Congo (Kinshasa)',null,0),
('Y1','\N','Yellowstone Club Private Shuttle','United States','US',0),
('YD','\N','Gomelavia','Belarus','BY',0),
('YE','YEL','Yellowtail','United States','US',0),
('YH','\N','Yangon Airways Ltd.','Burma',null,0),
('YL','LLM','Yamal Airlines','Russia',null,0),
('YS','RAE','Régional','France','FR',0),
('YV','ASH','Mesa Airlines','United States','US',0),
('YW','ANE','Air Nostrum','Spain','ES',0),
('YX','MEP','Midwest Airlines','United States','US',0),
('YY','VWA','Virginwings','Germany','DE',0),
('YZ','YZZ','LSM AIRLINES','Russia',null,0),
('Z0','Z9H','All Argentina Express','Argentina','AR',0),
('Z5','IIR','INAVIA Internacional','Argentina','AR',0),
('Z7','\N','REDjet','Barbados','BB',0),
('ZA','CYD','Access Air','United States','US',0),
('ZC','KGO','Korongo Airlines','Congo (Kinshasa)',null,0),
('ZF','\N','Athens Airways','Greece','GR',0),
('ZG','VVM','Viva Macau','Macao','MO',0),
('ZJ','\N','Zambezi Airlines (ZMA)','Zambia','ZM',0),
('ZN','ZNA','Zenith International Airline','Thailand','TH',0),
('ZP','ZZZ','Zabaykalskii Airlines','Russia',null,0),
('ZQ','LOC','Locair','United States','US',0),
('ZS','SMY','Sama Airlines','Saudi Arabia','SA',0),
('ZT','T9P','Tomp Airlines','Chile','CL',0),
('ZV','VAX','V Air','Taiwan',null,0),
('ZW','AWI','Air Wisconsin','United States','US',0),
('ZX','ZXY','Japan Regio','Japan','JP',0),
('ZY','ADE','Ada Air','Albania','AL',0),
('ZZ','\N','Zz','Belgium','BE',0),
('\N','TYR','Tyrolean Airways','\N',null,0),
('^^','\N','Whitaker Air','Australia','AU',0),
('АЯ','\N','Аэросервис','Russia',null,0),
('МИ','\N','KMV','Russia',null,0),
('ЯП','\N','Polar Airlines','Russia',null,0)
on conflict (iata) do update set icao=excluded.icao,name=excluded.name,country=excluded.country,country_code=excluded.country_code,route_count=excluded.route_count;

