-- ═══════════════════════════════════════════════════════════════════
--  APATMENTO · SHADOW ADS  — schema
--  ───────────────────────────────────────────────────────────────────
--  Shadow ads are non-invasive, behaviourally-targeted creatives that
--  surface behind or beside the content a guest is already engaging
--  with — never over it. Placement, timing and audience are decided by
--  the client-side intelligence engine (apa-shadow.js) reading live
--  ApaSignal intent, then reconciled here for reporting.
--
--  Separate table from ad_campaigns on purpose: shadow ads have their
--  own targeting model (behaviour + surface + position + psychology)
--  and their own delivery rules. Normal ads are untouched.
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.shadow_ads (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now(),
  updated_at        timestamptz default now(),

  -- identity
  advertiser        text not null,
  title             text not null,               -- internal name
  active            boolean default true,
  status            text default 'live',          -- live | paused | draft
  priority          int  default 5,               -- 1..10, higher wins ties

  -- creative
  media_type        text default 'image',         -- image | video
  media_url         text,                          -- jpg/webp/png or mp4
  poster_url        text,                          -- video first frame
  headline          text,
  sub_text          text,
  cta_text          text default 'View',
  cta_url           text,                          -- where a click goes
  theme_gradient    text default 'linear-gradient(135deg,#7C3AFF,#4F6DFF)',
  accent            text default '#7C3AFF',

  -- WHERE it may appear (service surfaces / pages)
  -- e.g. ["shopping","tours","apartments"] or ["all"]
  surfaces          jsonb default '["all"]'::jsonb,

  -- HOW it enters. rise = rises behind the focused card (signature),
  -- side | top | bottom = edge slide-in. auto lets the engine choose
  -- by device + surface for the least intrusive fit.
  position          text default 'auto',           -- auto | rise | side | top | bottom

  -- WHO / WHEN — behavioural gating read live from ApaSignal
  intent_min        int  default 0,                -- only show at/above this intent (0..100)
  intent_max        int  default 100,              -- and at/below this (e.g. don't distract hot checkout)
  min_dwell_s       int  default 6,                -- seconds on surface before eligible
  min_scroll_pct    int  default 0,                -- scroll depth gate
  reading_modes     jsonb default '["skim","scan","browse","read"]'::jsonb, -- never on 'bounce'
  device            text default 'all',            -- all | mobile | desktop | tablet
  keywords          jsonb default '[]'::jsonb,     -- match against search/category context

  -- delivery discipline (anti-annoyance)
  max_per_session   int  default 1,                -- times a single visitor sees it per session
  cooldown_s        int  default 90,               -- min gap between ANY two shadow ads
  dwell_show_s      int  default 7,                -- how long it stays before auto-retracting
  weight            int  default 1,                -- relative rotation weight

  -- flight & budget
  start_date        date,
  end_date          date,
  budget            numeric,

  -- live counters
  impressions       bigint default 0,             -- IAB-viewable surfaces
  clicks            bigint default 0,
  dismissals        bigint default 0,             -- user closed it early
  spend             numeric default 0
);

create index if not exists idx_shadow_active on public.shadow_ads (active, status);
create index if not exists idx_shadow_priority on public.shadow_ads (priority desc);

-- Per-event ledger — powers behaviour learning + honest billing.
create table if not exists public.shadow_ad_events (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now(),
  ad_id         bigint references public.shadow_ads(id) on delete cascade,
  visitor_id    text,
  session_id    text,
  event         text,        -- viewable | click | dismiss | ignore
  surface       text,        -- page it fired on
  position      text,        -- rise | side | top | bottom
  intent_score  int,         -- guest's live intent at the moment
  reading_mode  text,
  dwell_ms      int,         -- how long it was on screen
  device        text
);

create index if not exists idx_shadow_ev_ad on public.shadow_ad_events (ad_id);
create index if not exists idx_shadow_ev_visitor on public.shadow_ad_events (visitor_id);
create index if not exists idx_shadow_ev_created on public.shadow_ad_events (created_at desc);

-- ── Atomic counter RPCs (fire-and-forget from the client) ──
create or replace function public.increment_shadow_impression(p_ad_id bigint)
returns void language sql as $$
  update public.shadow_ads set impressions = impressions + 1 where id = p_ad_id;
$$;

create or replace function public.increment_shadow_click(p_ad_id bigint)
returns void language sql as $$
  update public.shadow_ads set clicks = clicks + 1 where id = p_ad_id;
$$;

create or replace function public.increment_shadow_dismiss(p_ad_id bigint)
returns void language sql as $$
  update public.shadow_ads set dismissals = dismissals + 1 where id = p_ad_id;
$$;

-- ── RLS ──
alter table public.shadow_ads       enable row level security;
alter table public.shadow_ad_events enable row level security;

-- Public may read only live, active creatives (delivery).
drop policy if exists shadow_read_public on public.shadow_ads;
create policy shadow_read_public on public.shadow_ads
  for select using (active = true and status = 'live');

-- Public may insert events (impression/click ledger) but never read them.
drop policy if exists shadow_ev_insert on public.shadow_ad_events;
create policy shadow_ev_insert on public.shadow_ad_events
  for insert with check (true);

-- Admin / operator management (mirrors ad_campaigns access model).
drop policy if exists "Admin full access shadow_ads" on public.shadow_ads;
create policy "Admin full access shadow_ads" on public.shadow_ads
  for all using (is_admin()) with check (is_admin());

drop policy if exists op_shadow_select on public.shadow_ads;
create policy op_shadow_select on public.shadow_ads
  for select to authenticated using (is_operator());

drop policy if exists op_shadow_insert on public.shadow_ads;
create policy op_shadow_insert on public.shadow_ads
  for insert to authenticated with check (is_operator());

drop policy if exists op_shadow_update on public.shadow_ads;
create policy op_shadow_update on public.shadow_ads
  for update to authenticated using (is_operator());

drop policy if exists op_shadow_delete on public.shadow_ads;
create policy op_shadow_delete on public.shadow_ads
  for delete to authenticated using (is_operator());

drop policy if exists "Admin read shadow_events" on public.shadow_ad_events;
create policy "Admin read shadow_events" on public.shadow_ad_events
  for select using (is_admin() or is_operator());
