-- ═══════════════════════════════════════════════════════════════════════════
-- TEST FIXTURE · the slice of production the growth engine reads
-- ─────────────────────────────────────────────────────────────────────────
-- Column names and types mirror the live tables (checked against project
-- gfwgbgdvxtocwhilrtdw on 2026-10-09), including the awkward ones: beds,
-- baths and max_guests are text on listings; photos are text[] on listings
-- and jsonb everywhere else; tours and events are keyed by bigint while
-- listings and cars are keyed by uuid. A fixture that tidied those up would let the
-- migration pass here and fail in production.
-- ═══════════════════════════════════════════════════════════════════════════

do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then create role anon nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then create role authenticated nologin; end if;
  if not exists (select 1 from pg_roles where rolname = 'service_role') then create role service_role nologin; end if;
end $$;

create extension if not exists pgcrypto;

create schema if not exists cabana_admin;
create or replace function public.is_admin() returns boolean language sql stable as $$
  select coalesce(current_setting('test.admin', true), '') = 'yes';
$$;
create or replace function cabana_admin.guard() returns void language plpgsql stable as $$
begin
  if not public.is_admin() then raise exception 'admin_required' using errcode = '42501'; end if;
end $$;

create schema if not exists cabana_ops;
create table cabana_ops.cron_config (key text primary key, value text);
insert into cabana_ops.cron_config values ('cron_secret', 'test-secret');

create schema if not exists net;
create table net.calls (id serial, url text, headers jsonb, body jsonb);
create or replace function net.http_post(url text, body jsonb default '{}', params jsonb default '{}',
                                         headers jsonb default '{}', timeout_milliseconds int default 5000)
returns bigint language plpgsql as $$
begin
  insert into net.calls (url, headers, body) values (url, headers, body);
  return 1;
end $$;

create table public.profiles (id uuid primary key, first_name text, last_name text, verified boolean, last_role text);

create table public.site_settings (key text primary key, value text, label text, type text, category text,
                                   updated_at timestamptz, updated_by text);

create table public.listings (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid, host_id uuid, type text, title text, country text, city text, area text, street text,
  beds text, baths text, max_guests text, floor text, sqm text, description text,
  amenities text[], photos text[], currency text, price_night numeric, price_week numeric, price_month numeric,
  deposit numeric, min_nights int, checkin_time text, checkout_time text, smoking boolean, pets boolean,
  events boolean, children boolean, instant_book boolean, cancel_policy text, house_rules text,
  status text default 'pending', created_at timestamptz default now(), is_active boolean default false,
  listing_type text, price_per_night numeric, location text, property_type text, bedrooms int,
  avg_rating numeric default 0, review_count int default 0, internal_score numeric default 50,
  booking_count int default 0, days_listed int, bathrooms int, approved_at timestamptz, deleted_at timestamptz,
  featured boolean default false, views int default 0, updated_at timestamptz default now(),
  lat numeric, lng numeric, size_sqm numeric, contact_whatsapp text, contact_phone text, contact_email text,
  latitude numeric, longitude numeric, service text, extras jsonb, tour_3d_status text default 'none',
  tour_3d_url text, booking_model text, day_pass_enabled boolean, day_pass_price numeric, host_verified boolean default false
);

create table public.restaurant_profiles (
  listing_id uuid primary key, tagline text, cuisines text[], signature_dish text, avg_price numeric,
  min_order numeric, delivery_mins int, opens_at text, closes_at text, open_days text[], serves_delivery boolean,
  serves_pickup boolean, serves_dine_in boolean, halal boolean, hero_photo text
);

create table public.reviews (
  id uuid primary key default gen_random_uuid(), listing_id uuid, listing_name text, guest_id uuid,
  guest_name text, rating int, review_text text, host_reply text, created_at timestamptz default now()
);

create table public.tour_operators (id bigint generated by default as identity primary key, name text, verified boolean,
                                    tagline text, status text);
create table public.tours (
  id bigint generated by default as identity primary key, operator_id bigint, owner_id uuid, slug text, title text,
  summary text, description text, category text, destination text, county text, country text,
  start_point text, meeting_point text, duration_label text, duration_hours numeric, days int, price_kes int,
  child_price_kes int, price_basis text, group_min int, group_max int, schedule_type text, next_departure date,
  departure_days jsonb, cover_url text, photos jsonb, tags jsonb, highlights jsonb, includes_list jsonb,
  excludes_list jsonb, itinerary jsonb, what_to_bring jsonb, languages jsonb, cancellation text,
  accessibility text, status text, published_at timestamptz, featured boolean, sort_weight int, views int,
  created_at timestamptz default now(), updated_at timestamptz default now(), latitude numeric, longitude numeric,
  departure_time text
);

create table public.event_organisers (id bigint generated by default as identity primary key, name text, verified boolean);
create table public.events (
  id bigint generated by default as identity primary key, organiser_id bigint, owner_id uuid, slug text, title text,
  tagline text, description text, category text, starts_at timestamptz, ends_at timestamptz, doors_at timestamptz,
  timezone text, venue text, address text, city text, country text, lat numeric, lng numeric, tiers jsonb,
  price_from int, currency text, capacity int, tickets_sold int default 0, cover_url text, photos jsonb,
  videos jsonb, lineup jsonb, tags jsonb, age_limit text, dress_code text, refund_policy text, status text,
  published_at timestamptz, featured boolean, sort_weight int, views int, created_at timestamptz default now(),
  updated_at timestamptz default now(), latitude numeric, longitude numeric
);

create table public.car_operators (
  id uuid primary key default gen_random_uuid(), name text, city text, country_code char(2), verified boolean,
  rating numeric, currency_code text, paused_until timestamptz, completed_hires int, response_mins int
);
create table public.car_fleet (
  id uuid primary key default gen_random_uuid(), operator_id uuid, make text, model text, variant text, year int,
  plate text, class text, body text, seats int, ground_clearance_mm int, drive text, transmission text, fuel text,
  aircon boolean, day_rate int, chauffeur_uplift_metro int, chauffeur_uplift_upcountry int, deposit int, fuel_policy text, mileage_cap_km int, min_hire_days int,
  min_driver_age int, cross_border_ok boolean, extras jsonb, photos jsonb, status text,
  created_at timestamptz default now(), weekly_discount_pct numeric, monthly_discount_pct numeric, colour text,
  description text, features text[], instant_book boolean, delivery_ok boolean, updated_at timestamptz default now()
);

create table public.support_threads (
  id uuid primary key default gen_random_uuid(), user_id uuid, guest_key text, status text default 'apa',
  escalated_at timestamptz, apa_resolved boolean default false, csat smallint, category text,
  created_at timestamptz default now(), last_message_at timestamptz default now()
);
